/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import AnalysisResult from "../model/AnalysisResult";

/**
 * Analysis service.
 * @module api/AnalysisApi
 * @version 0.1.0
 */
export default class AnalysisApi {
  /**
   * Constructs a new AnalysisApi.
   * @alias module:api/AnalysisApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Run Cld File
   * @param {module:model/CldMethod} method
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @param {Object} opts Optional parameters
   * @param {Number} opts.npReference
   * @param {Number} opts.m0Init
   * @param {Number} opts.dInit
   * @param {Number} opts.alphaTInit
   * @param {Number} opts.alphaCInit
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runCldFileWithHttpInfo(method, ucs, uts, file, opts) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runCldFile"
      );
    }
    // verify the required parameter 'ucs' is set
    if (ucs === undefined || ucs === null) {
      throw new Error(
        "Missing the required parameter 'ucs' when calling runCldFile"
      );
    }
    // verify the required parameter 'uts' is set
    if (uts === undefined || uts === null) {
      throw new Error(
        "Missing the required parameter 'uts' when calling runCldFile"
      );
    }
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling runCldFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
      ucs: ucs,
      uts: uts,
      np_reference: opts["npReference"],
      m0_init: opts["m0Init"],
      d_init: opts["dInit"],
      alpha_t_init: opts["alphaTInit"],
      alpha_c_init: opts["alphaCInit"],
    };
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/cld/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Cld File
   * @param {module:model/CldMethod} method
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @param {Object} opts Optional parameters
   * @param {Number} opts.npReference
   * @param {Number} opts.m0Init
   * @param {Number} opts.dInit
   * @param {Number} opts.alphaTInit
   * @param {Number} opts.alphaCInit
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runCldFile(method, ucs, uts, file, opts) {
    return this.runCldFileWithHttpInfo(method, ucs, uts, file, opts).then(
      function (response_and_data) {
        return response_and_data.data;
      }
    );
  }

  /**
   * Run Cld Piecewiselinear From Sn File
   * @param {module:model/SnCurveMethod} snMethod
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @param {Object} opts Optional parameters
   * @param {Number} opts.confidenceInterval
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runCldPiecewiselinearFromSnFileWithHttpInfo(snMethod, ucs, uts, file, opts) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'snMethod' is set
    if (snMethod === undefined || snMethod === null) {
      throw new Error(
        "Missing the required parameter 'snMethod' when calling runCldPiecewiselinearFromSnFile"
      );
    }
    // verify the required parameter 'ucs' is set
    if (ucs === undefined || ucs === null) {
      throw new Error(
        "Missing the required parameter 'ucs' when calling runCldPiecewiselinearFromSnFile"
      );
    }
    // verify the required parameter 'uts' is set
    if (uts === undefined || uts === null) {
      throw new Error(
        "Missing the required parameter 'uts' when calling runCldPiecewiselinearFromSnFile"
      );
    }
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling runCldPiecewiselinearFromSnFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      snMethod: snMethod,
      ucs: ucs,
      uts: uts,
      confidenceInterval: opts["confidenceInterval"],
    };
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/cld/piecewiselinear-from-sn/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Cld Piecewiselinear From Sn File
   * @param {module:model/SnCurveMethod} snMethod
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @param {Object} opts Optional parameters
   * @param {Number} opts.confidenceInterval
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runCldPiecewiselinearFromSnFile(snMethod, ucs, uts, file, opts) {
    return this.runCldPiecewiselinearFromSnFileWithHttpInfo(
      snMethod,
      ucs,
      uts,
      file,
      opts
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Cld Piecewisenonlinear From Sn File
   * @param {module:model/SnCurveMethod} snMethod
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @param {Object} opts Optional parameters
   * @param {Number} opts.confidenceInterval
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runCldPiecewisenonlinearFromSnFileWithHttpInfo(
    snMethod,
    ucs,
    uts,
    file,
    opts
  ) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'snMethod' is set
    if (snMethod === undefined || snMethod === null) {
      throw new Error(
        "Missing the required parameter 'snMethod' when calling runCldPiecewisenonlinearFromSnFile"
      );
    }
    // verify the required parameter 'ucs' is set
    if (ucs === undefined || ucs === null) {
      throw new Error(
        "Missing the required parameter 'ucs' when calling runCldPiecewisenonlinearFromSnFile"
      );
    }
    // verify the required parameter 'uts' is set
    if (uts === undefined || uts === null) {
      throw new Error(
        "Missing the required parameter 'uts' when calling runCldPiecewisenonlinearFromSnFile"
      );
    }
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling runCldPiecewisenonlinearFromSnFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      snMethod: snMethod,
      ucs: ucs,
      uts: uts,
      confidenceInterval: opts["confidenceInterval"],
    };
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/cld/piecewisenonlinear-from-sn/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Cld Piecewisenonlinear From Sn File
   * @param {module:model/SnCurveMethod} snMethod
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @param {Object} opts Optional parameters
   * @param {Number} opts.confidenceInterval
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runCldPiecewisenonlinearFromSnFile(snMethod, ucs, uts, file, opts) {
    return this.runCldPiecewisenonlinearFromSnFileWithHttpInfo(
      snMethod,
      ucs,
      uts,
      file,
      opts
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Cycle Counting File
   * @param {module:model/CycleCountingMethod} method
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link File} and HTTP response
   */
  runCycleCountingFileWithHttpInfo(method, file) {
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runCycleCountingFile"
      );
    }
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling runCycleCountingFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
    };
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = File;
    return this.apiClient.callApi(
      "/analysis/cycleCounting/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Cycle Counting File
   * @param {module:model/CycleCountingMethod} method
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link File}
   */
  runCycleCountingFile(method, file) {
    return this.runCycleCountingFileWithHttpInfo(method, file).then(function (
      response_and_data
    ) {
      return response_and_data.data;
    });
  }

  /**
   * Run Damage Summation File
   * @param {module:model/DamageSummationMethod} method
   * @param {File} sncFile
   * @param {File} cycFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link File} and HTTP response
   */
  runDamageSummationFileWithHttpInfo(method, sncFile, cycFile) {
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runDamageSummationFile"
      );
    }
    // verify the required parameter 'sncFile' is set
    if (sncFile === undefined || sncFile === null) {
      throw new Error(
        "Missing the required parameter 'sncFile' when calling runDamageSummationFile"
      );
    }
    // verify the required parameter 'cycFile' is set
    if (cycFile === undefined || cycFile === null) {
      throw new Error(
        "Missing the required parameter 'cycFile' when calling runDamageSummationFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
    };
    let headerParams = {};
    let formParams = {
      sncFile: sncFile,
      cycFile: cycFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = File;
    return this.apiClient.callApi(
      "/analysis/damageSummation/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Damage Summation File
   * @param {module:model/DamageSummationMethod} method
   * @param {File} sncFile
   * @param {File} cycFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link File}
   */
  runDamageSummationFile(method, sncFile, cycFile) {
    return this.runDamageSummationFileWithHttpInfo(
      method,
      sncFile,
      cycFile
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure Fawazellyin File
   * @param {module:model/FatigueModel} snModel
   * @param {Number} referenceAngle
   * @param {Number} referenceStaticStrength
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} targetStaticStrength
   * @param {File} sncFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureFawazellyinFileWithHttpInfo(
    snModel,
    referenceAngle,
    referenceStaticStrength,
    desirableAngle,
    targetStressRatio,
    targetStaticStrength,
    sncFile
  ) {
    let postBody = null;
    // verify the required parameter 'snModel' is set
    if (snModel === undefined || snModel === null) {
      throw new Error(
        "Missing the required parameter 'snModel' when calling runFatigueFailureFawazellyinFile"
      );
    }
    // verify the required parameter 'referenceAngle' is set
    if (referenceAngle === undefined || referenceAngle === null) {
      throw new Error(
        "Missing the required parameter 'referenceAngle' when calling runFatigueFailureFawazellyinFile"
      );
    }
    // verify the required parameter 'referenceStaticStrength' is set
    if (
      referenceStaticStrength === undefined ||
      referenceStaticStrength === null
    ) {
      throw new Error(
        "Missing the required parameter 'referenceStaticStrength' when calling runFatigueFailureFawazellyinFile"
      );
    }
    // verify the required parameter 'desirableAngle' is set
    if (desirableAngle === undefined || desirableAngle === null) {
      throw new Error(
        "Missing the required parameter 'desirableAngle' when calling runFatigueFailureFawazellyinFile"
      );
    }
    // verify the required parameter 'targetStressRatio' is set
    if (targetStressRatio === undefined || targetStressRatio === null) {
      throw new Error(
        "Missing the required parameter 'targetStressRatio' when calling runFatigueFailureFawazellyinFile"
      );
    }
    // verify the required parameter 'targetStaticStrength' is set
    if (targetStaticStrength === undefined || targetStaticStrength === null) {
      throw new Error(
        "Missing the required parameter 'targetStaticStrength' when calling runFatigueFailureFawazellyinFile"
      );
    }
    // verify the required parameter 'sncFile' is set
    if (sncFile === undefined || sncFile === null) {
      throw new Error(
        "Missing the required parameter 'sncFile' when calling runFatigueFailureFawazellyinFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      snModel: snModel,
      referenceAngle: referenceAngle,
      referenceStaticStrength: referenceStaticStrength,
      desirableAngle: desirableAngle,
      targetStressRatio: targetStressRatio,
      targetStaticStrength: targetStaticStrength,
    };
    let headerParams = {};
    let formParams = {
      sncFile: sncFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/fawazEllyin/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure Fawazellyin File
   * @param {module:model/FatigueModel} snModel
   * @param {Number} referenceAngle
   * @param {Number} referenceStaticStrength
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} targetStaticStrength
   * @param {File} sncFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureFawazellyinFile(
    snModel,
    referenceAngle,
    referenceStaticStrength,
    desirableAngle,
    targetStressRatio,
    targetStaticStrength,
    sncFile
  ) {
    return this.runFatigueFailureFawazellyinFileWithHttpInfo(
      snModel,
      referenceAngle,
      referenceStaticStrength,
      desirableAngle,
      targetStressRatio,
      targetStaticStrength,
      sncFile
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure File
   * @param {module:model/FatigueFailureMethod} method
   * @param {module:model/FatigueModel} snModel
   * @param {Number} desirableAngle
   * @param {Number} offAxisAngle
   * @param {File} xFile
   * @param {File} yFile
   * @param {File} fFile
   * @param {Object} opts Optional parameters
   * @param {Number} opts.offAxisAngle2
   * @param {Number} opts.tensileTransverseStrength
   * @param {Number} opts.compressiveTransverseStrength
   * @param {Number} opts.shearStrength
   * @param {Number} opts.tensileStrength1
   * @param {Number} opts.compressiveStrength1
   * @param {Number} opts.tensileStrength2
   * @param {Number} opts.compressiveStrength2
   * @param {Number} opts.tensileStrengthAtDesirableAngle
   * @param {Number} opts.compressiveStrengthAtDesirableAngle
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureFileWithHttpInfo(
    method,
    snModel,
    desirableAngle,
    offAxisAngle,
    xFile,
    yFile,
    fFile,
    opts
  ) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'snModel' is set
    if (snModel === undefined || snModel === null) {
      throw new Error(
        "Missing the required parameter 'snModel' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'desirableAngle' is set
    if (desirableAngle === undefined || desirableAngle === null) {
      throw new Error(
        "Missing the required parameter 'desirableAngle' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'offAxisAngle' is set
    if (offAxisAngle === undefined || offAxisAngle === null) {
      throw new Error(
        "Missing the required parameter 'offAxisAngle' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'xFile' is set
    if (xFile === undefined || xFile === null) {
      throw new Error(
        "Missing the required parameter 'xFile' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'yFile' is set
    if (yFile === undefined || yFile === null) {
      throw new Error(
        "Missing the required parameter 'yFile' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'fFile' is set
    if (fFile === undefined || fFile === null) {
      throw new Error(
        "Missing the required parameter 'fFile' when calling runFatigueFailureFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
      snModel: snModel,
      desirableAngle: desirableAngle,
      offAxisAngle: offAxisAngle,
      offAxisAngle2: opts["offAxisAngle2"],
      tensile_transverse_strength: opts["tensileTransverseStrength"],
      compressive_transverse_strength: opts["compressiveTransverseStrength"],
      shear_strength: opts["shearStrength"],
      tensile_strength1: opts["tensileStrength1"],
      compressive_strength1: opts["compressiveStrength1"],
      tensile_strength2: opts["tensileStrength2"],
      compressive_strength2: opts["compressiveStrength2"],
      tensile_strength_at_desirable_angle:
        opts["tensileStrengthAtDesirableAngle"],
      compressive_strength_at_desirable_angle:
        opts["compressiveStrengthAtDesirableAngle"],
    };
    let headerParams = {};
    let formParams = {
      xFile: xFile,
      yFile: yFile,
      fFile: fFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure File
   * @param {module:model/FatigueFailureMethod} method
   * @param {module:model/FatigueModel} snModel
   * @param {Number} desirableAngle
   * @param {Number} offAxisAngle
   * @param {File} xFile
   * @param {File} yFile
   * @param {File} fFile
   * @param {Object} opts Optional parameters
   * @param {Number} opts.offAxisAngle2
   * @param {Number} opts.tensileTransverseStrength
   * @param {Number} opts.compressiveTransverseStrength
   * @param {Number} opts.shearStrength
   * @param {Number} opts.tensileStrength1
   * @param {Number} opts.compressiveStrength1
   * @param {Number} opts.tensileStrength2
   * @param {Number} opts.compressiveStrength2
   * @param {Number} opts.tensileStrengthAtDesirableAngle
   * @param {Number} opts.compressiveStrengthAtDesirableAngle
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureFile(
    method,
    snModel,
    desirableAngle,
    offAxisAngle,
    xFile,
    yFile,
    fFile,
    opts
  ) {
    return this.runFatigueFailureFileWithHttpInfo(
      method,
      snModel,
      desirableAngle,
      offAxisAngle,
      xFile,
      yFile,
      fFile,
      opts
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure Ftpf File
   * @param {module:model/FatigueModel} snModel
   * @param {Number} desirableAngle
   * @param {Number} offAxisAngle
   * @param {File} xFile
   * @param {File} yFile
   * @param {File} fFile
   * @param {Object} opts Optional parameters
   * @param {File} opts.xcFile
   * @param {File} opts.ycFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureFtpfFileWithHttpInfo(
    snModel,
    desirableAngle,
    offAxisAngle,
    xFile,
    yFile,
    fFile,
    opts
  ) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'snModel' is set
    if (snModel === undefined || snModel === null) {
      throw new Error(
        "Missing the required parameter 'snModel' when calling runFatigueFailureFtpfFile"
      );
    }
    // verify the required parameter 'desirableAngle' is set
    if (desirableAngle === undefined || desirableAngle === null) {
      throw new Error(
        "Missing the required parameter 'desirableAngle' when calling runFatigueFailureFtpfFile"
      );
    }
    // verify the required parameter 'offAxisAngle' is set
    if (offAxisAngle === undefined || offAxisAngle === null) {
      throw new Error(
        "Missing the required parameter 'offAxisAngle' when calling runFatigueFailureFtpfFile"
      );
    }
    // verify the required parameter 'xFile' is set
    if (xFile === undefined || xFile === null) {
      throw new Error(
        "Missing the required parameter 'xFile' when calling runFatigueFailureFtpfFile"
      );
    }
    // verify the required parameter 'yFile' is set
    if (yFile === undefined || yFile === null) {
      throw new Error(
        "Missing the required parameter 'yFile' when calling runFatigueFailureFtpfFile"
      );
    }
    // verify the required parameter 'fFile' is set
    if (fFile === undefined || fFile === null) {
      throw new Error(
        "Missing the required parameter 'fFile' when calling runFatigueFailureFtpfFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      snModel: snModel,
      desirableAngle: desirableAngle,
      offAxisAngle: offAxisAngle,
    };
    let headerParams = {};
    let formParams = {
      xFile: xFile,
      yFile: yFile,
      fFile: fFile,
      xcFile: opts["xcFile"],
      ycFile: opts["ycFile"],
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/ftpf/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure Ftpf File
   * @param {module:model/FatigueModel} snModel
   * @param {Number} desirableAngle
   * @param {Number} offAxisAngle
   * @param {File} xFile
   * @param {File} yFile
   * @param {File} fFile
   * @param {Object} opts Optional parameters
   * @param {File} opts.xcFile
   * @param {File} opts.ycFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureFtpfFile(
    snModel,
    desirableAngle,
    offAxisAngle,
    xFile,
    yFile,
    fFile,
    opts
  ) {
    return this.runFatigueFailureFtpfFileWithHttpInfo(
      snModel,
      desirableAngle,
      offAxisAngle,
      xFile,
      yFile,
      fFile,
      opts
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure Hashinrotem File
   * @param {module:model/FatigueModel} snModel
   * @param {Number} desirableAngle
   * @param {Number} offAxisAngle1
   * @param {Number} offAxisAngle2
   * @param {Number} tensileTransverseStrength
   * @param {Number} shearStrength
   * @param {Number} tensileStrength1
   * @param {Number} tensileStrength2
   * @param {Number} tensileStrengthAtDesirableAngle
   * @param {Number} tensileAxialStrength
   * @param {module:model/HashinRotemPanelType} panel2Type
   * @param {module:model/HashinRotemPanelType} panel3Type
   * @param {File} xFile
   * @param {File} panel2File
   * @param {File} panel3File
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureHashinrotemFileWithHttpInfo(
    snModel,
    desirableAngle,
    offAxisAngle1,
    offAxisAngle2,
    tensileTransverseStrength,
    shearStrength,
    tensileStrength1,
    tensileStrength2,
    tensileStrengthAtDesirableAngle,
    tensileAxialStrength,
    panel2Type,
    panel3Type,
    xFile,
    panel2File,
    panel3File
  ) {
    let postBody = null;
    // verify the required parameter 'snModel' is set
    if (snModel === undefined || snModel === null) {
      throw new Error(
        "Missing the required parameter 'snModel' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'desirableAngle' is set
    if (desirableAngle === undefined || desirableAngle === null) {
      throw new Error(
        "Missing the required parameter 'desirableAngle' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'offAxisAngle1' is set
    if (offAxisAngle1 === undefined || offAxisAngle1 === null) {
      throw new Error(
        "Missing the required parameter 'offAxisAngle1' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'offAxisAngle2' is set
    if (offAxisAngle2 === undefined || offAxisAngle2 === null) {
      throw new Error(
        "Missing the required parameter 'offAxisAngle2' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'tensileTransverseStrength' is set
    if (
      tensileTransverseStrength === undefined ||
      tensileTransverseStrength === null
    ) {
      throw new Error(
        "Missing the required parameter 'tensileTransverseStrength' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'shearStrength' is set
    if (shearStrength === undefined || shearStrength === null) {
      throw new Error(
        "Missing the required parameter 'shearStrength' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'tensileStrength1' is set
    if (tensileStrength1 === undefined || tensileStrength1 === null) {
      throw new Error(
        "Missing the required parameter 'tensileStrength1' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'tensileStrength2' is set
    if (tensileStrength2 === undefined || tensileStrength2 === null) {
      throw new Error(
        "Missing the required parameter 'tensileStrength2' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'tensileStrengthAtDesirableAngle' is set
    if (
      tensileStrengthAtDesirableAngle === undefined ||
      tensileStrengthAtDesirableAngle === null
    ) {
      throw new Error(
        "Missing the required parameter 'tensileStrengthAtDesirableAngle' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'tensileAxialStrength' is set
    if (tensileAxialStrength === undefined || tensileAxialStrength === null) {
      throw new Error(
        "Missing the required parameter 'tensileAxialStrength' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'panel2Type' is set
    if (panel2Type === undefined || panel2Type === null) {
      throw new Error(
        "Missing the required parameter 'panel2Type' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'panel3Type' is set
    if (panel3Type === undefined || panel3Type === null) {
      throw new Error(
        "Missing the required parameter 'panel3Type' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'xFile' is set
    if (xFile === undefined || xFile === null) {
      throw new Error(
        "Missing the required parameter 'xFile' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'panel2File' is set
    if (panel2File === undefined || panel2File === null) {
      throw new Error(
        "Missing the required parameter 'panel2File' when calling runFatigueFailureHashinrotemFile"
      );
    }
    // verify the required parameter 'panel3File' is set
    if (panel3File === undefined || panel3File === null) {
      throw new Error(
        "Missing the required parameter 'panel3File' when calling runFatigueFailureHashinrotemFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      snModel: snModel,
      desirableAngle: desirableAngle,
      offAxisAngle1: offAxisAngle1,
      offAxisAngle2: offAxisAngle2,
      tensile_transverse_strength: tensileTransverseStrength,
      shear_strength: shearStrength,
      tensile_strength1: tensileStrength1,
      tensile_strength2: tensileStrength2,
      tensile_strength_at_desirable_angle: tensileStrengthAtDesirableAngle,
      tensile_axial_strength: tensileAxialStrength,
      panel2Type: panel2Type,
      panel3Type: panel3Type,
    };
    let headerParams = {};
    let formParams = {
      xFile: xFile,
      panel2File: panel2File,
      panel3File: panel3File,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/hashinRotem/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure Hashinrotem File
   * @param {module:model/FatigueModel} snModel
   * @param {Number} desirableAngle
   * @param {Number} offAxisAngle1
   * @param {Number} offAxisAngle2
   * @param {Number} tensileTransverseStrength
   * @param {Number} shearStrength
   * @param {Number} tensileStrength1
   * @param {Number} tensileStrength2
   * @param {Number} tensileStrengthAtDesirableAngle
   * @param {Number} tensileAxialStrength
   * @param {module:model/HashinRotemPanelType} panel2Type
   * @param {module:model/HashinRotemPanelType} panel3Type
   * @param {File} xFile
   * @param {File} panel2File
   * @param {File} panel3File
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureHashinrotemFile(
    snModel,
    desirableAngle,
    offAxisAngle1,
    offAxisAngle2,
    tensileTransverseStrength,
    shearStrength,
    tensileStrength1,
    tensileStrength2,
    tensileStrengthAtDesirableAngle,
    tensileAxialStrength,
    panel2Type,
    panel3Type,
    xFile,
    panel2File,
    panel3File
  ) {
    return this.runFatigueFailureHashinrotemFileWithHttpInfo(
      snModel,
      desirableAngle,
      offAxisAngle1,
      offAxisAngle2,
      tensileTransverseStrength,
      shearStrength,
      tensileStrength1,
      tensileStrength2,
      tensileStrengthAtDesirableAngle,
      tensileAxialStrength,
      panel2Type,
      panel3Type,
      xFile,
      panel2File,
      panel3File
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure Kawai File
   * @param {Number} referenceAngle
   * @param {Number} referenceStressRatio
   * @param {Number} referenceStaticStrength
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} tensileAxialStrength
   * @param {Number} tensileTransverseStrength
   * @param {Number} shearStrength
   * @param {File} aggFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureKawaiFileWithHttpInfo(
    referenceAngle,
    referenceStressRatio,
    referenceStaticStrength,
    desirableAngle,
    targetStressRatio,
    tensileAxialStrength,
    tensileTransverseStrength,
    shearStrength,
    aggFile
  ) {
    let postBody = null;
    // verify the required parameter 'referenceAngle' is set
    if (referenceAngle === undefined || referenceAngle === null) {
      throw new Error(
        "Missing the required parameter 'referenceAngle' when calling runFatigueFailureKawaiFile"
      );
    }
    // verify the required parameter 'referenceStressRatio' is set
    if (referenceStressRatio === undefined || referenceStressRatio === null) {
      throw new Error(
        "Missing the required parameter 'referenceStressRatio' when calling runFatigueFailureKawaiFile"
      );
    }
    // verify the required parameter 'referenceStaticStrength' is set
    if (
      referenceStaticStrength === undefined ||
      referenceStaticStrength === null
    ) {
      throw new Error(
        "Missing the required parameter 'referenceStaticStrength' when calling runFatigueFailureKawaiFile"
      );
    }
    // verify the required parameter 'desirableAngle' is set
    if (desirableAngle === undefined || desirableAngle === null) {
      throw new Error(
        "Missing the required parameter 'desirableAngle' when calling runFatigueFailureKawaiFile"
      );
    }
    // verify the required parameter 'targetStressRatio' is set
    if (targetStressRatio === undefined || targetStressRatio === null) {
      throw new Error(
        "Missing the required parameter 'targetStressRatio' when calling runFatigueFailureKawaiFile"
      );
    }
    // verify the required parameter 'tensileAxialStrength' is set
    if (tensileAxialStrength === undefined || tensileAxialStrength === null) {
      throw new Error(
        "Missing the required parameter 'tensileAxialStrength' when calling runFatigueFailureKawaiFile"
      );
    }
    // verify the required parameter 'tensileTransverseStrength' is set
    if (
      tensileTransverseStrength === undefined ||
      tensileTransverseStrength === null
    ) {
      throw new Error(
        "Missing the required parameter 'tensileTransverseStrength' when calling runFatigueFailureKawaiFile"
      );
    }
    // verify the required parameter 'shearStrength' is set
    if (shearStrength === undefined || shearStrength === null) {
      throw new Error(
        "Missing the required parameter 'shearStrength' when calling runFatigueFailureKawaiFile"
      );
    }
    // verify the required parameter 'aggFile' is set
    if (aggFile === undefined || aggFile === null) {
      throw new Error(
        "Missing the required parameter 'aggFile' when calling runFatigueFailureKawaiFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      referenceAngle: referenceAngle,
      referenceStressRatio: referenceStressRatio,
      referenceStaticStrength: referenceStaticStrength,
      desirableAngle: desirableAngle,
      targetStressRatio: targetStressRatio,
      tensile_axial_strength: tensileAxialStrength,
      tensile_transverse_strength: tensileTransverseStrength,
      shear_strength: shearStrength,
    };
    let headerParams = {};
    let formParams = {
      aggFile: aggFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/kawai/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure Kawai File
   * @param {Number} referenceAngle
   * @param {Number} referenceStressRatio
   * @param {Number} referenceStaticStrength
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} tensileAxialStrength
   * @param {Number} tensileTransverseStrength
   * @param {Number} shearStrength
   * @param {File} aggFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureKawaiFile(
    referenceAngle,
    referenceStressRatio,
    referenceStaticStrength,
    desirableAngle,
    targetStressRatio,
    tensileAxialStrength,
    tensileTransverseStrength,
    shearStrength,
    aggFile
  ) {
    return this.runFatigueFailureKawaiFileWithHttpInfo(
      referenceAngle,
      referenceStressRatio,
      referenceStaticStrength,
      desirableAngle,
      targetStressRatio,
      tensileAxialStrength,
      tensileTransverseStrength,
      shearStrength,
      aggFile
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure Shokriehtaheri File
   * @param {Number} referenceAngle
   * @param {Number} referenceStressRatio
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} tensileAxialStrength
   * @param {Number} compressiveAxialStrength
   * @param {Number} tensileTransverseStrength
   * @param {Number} compressiveTransverseStrength
   * @param {Number} shearStrength
   * @param {File} aggFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureShokriehtaheriFileWithHttpInfo(
    referenceAngle,
    referenceStressRatio,
    desirableAngle,
    targetStressRatio,
    tensileAxialStrength,
    compressiveAxialStrength,
    tensileTransverseStrength,
    compressiveTransverseStrength,
    shearStrength,
    aggFile
  ) {
    let postBody = null;
    // verify the required parameter 'referenceAngle' is set
    if (referenceAngle === undefined || referenceAngle === null) {
      throw new Error(
        "Missing the required parameter 'referenceAngle' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'referenceStressRatio' is set
    if (referenceStressRatio === undefined || referenceStressRatio === null) {
      throw new Error(
        "Missing the required parameter 'referenceStressRatio' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'desirableAngle' is set
    if (desirableAngle === undefined || desirableAngle === null) {
      throw new Error(
        "Missing the required parameter 'desirableAngle' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'targetStressRatio' is set
    if (targetStressRatio === undefined || targetStressRatio === null) {
      throw new Error(
        "Missing the required parameter 'targetStressRatio' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'tensileAxialStrength' is set
    if (tensileAxialStrength === undefined || tensileAxialStrength === null) {
      throw new Error(
        "Missing the required parameter 'tensileAxialStrength' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'compressiveAxialStrength' is set
    if (
      compressiveAxialStrength === undefined ||
      compressiveAxialStrength === null
    ) {
      throw new Error(
        "Missing the required parameter 'compressiveAxialStrength' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'tensileTransverseStrength' is set
    if (
      tensileTransverseStrength === undefined ||
      tensileTransverseStrength === null
    ) {
      throw new Error(
        "Missing the required parameter 'tensileTransverseStrength' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'compressiveTransverseStrength' is set
    if (
      compressiveTransverseStrength === undefined ||
      compressiveTransverseStrength === null
    ) {
      throw new Error(
        "Missing the required parameter 'compressiveTransverseStrength' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'shearStrength' is set
    if (shearStrength === undefined || shearStrength === null) {
      throw new Error(
        "Missing the required parameter 'shearStrength' when calling runFatigueFailureShokriehtaheriFile"
      );
    }
    // verify the required parameter 'aggFile' is set
    if (aggFile === undefined || aggFile === null) {
      throw new Error(
        "Missing the required parameter 'aggFile' when calling runFatigueFailureShokriehtaheriFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      referenceAngle: referenceAngle,
      referenceStressRatio: referenceStressRatio,
      desirableAngle: desirableAngle,
      targetStressRatio: targetStressRatio,
      tensile_axial_strength: tensileAxialStrength,
      compressive_axial_strength: compressiveAxialStrength,
      tensile_transverse_strength: tensileTransverseStrength,
      compressive_transverse_strength: compressiveTransverseStrength,
      shear_strength: shearStrength,
    };
    let headerParams = {};
    let formParams = {
      aggFile: aggFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/shokriehTaheri/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure Shokriehtaheri File
   * @param {Number} referenceAngle
   * @param {Number} referenceStressRatio
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} tensileAxialStrength
   * @param {Number} compressiveAxialStrength
   * @param {Number} tensileTransverseStrength
   * @param {Number} compressiveTransverseStrength
   * @param {Number} shearStrength
   * @param {File} aggFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureShokriehtaheriFile(
    referenceAngle,
    referenceStressRatio,
    desirableAngle,
    targetStressRatio,
    tensileAxialStrength,
    compressiveAxialStrength,
    tensileTransverseStrength,
    compressiveTransverseStrength,
    shearStrength,
    aggFile
  ) {
    return this.runFatigueFailureShokriehtaheriFileWithHttpInfo(
      referenceAngle,
      referenceStressRatio,
      desirableAngle,
      targetStressRatio,
      tensileAxialStrength,
      compressiveAxialStrength,
      tensileTransverseStrength,
      compressiveTransverseStrength,
      shearStrength,
      aggFile
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Sn Curve File
   * @param {module:model/SnCurveMethod} method
   * @param {File} file
   * @param {Object} opts Optional parameters
   * @param {Number} opts.confidenceInterval
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runSnCurveFileWithHttpInfo(method, file, opts) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runSnCurveFile"
      );
    }
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling runSnCurveFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
      confidenceInterval: opts["confidenceInterval"],
    };
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/snCurve/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Sn Curve File
   * @param {module:model/SnCurveMethod} method
   * @param {File} file
   * @param {Object} opts Optional parameters
   * @param {Number} opts.confidenceInterval
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runSnCurveFile(method, file, opts) {
    return this.runSnCurveFileWithHttpInfo(method, file, opts).then(function (
      response_and_data
    ) {
      return response_and_data.data;
    });
  }
}
