/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import AnalysisResult from "../model/AnalysisResult";

/**
 * Analysis service.
 * @module api/AnalysisApi
 * @version 0.1.0
 */
export default class AnalysisApi {
  /**
   * Constructs a new AnalysisApi.
   * @alias module:api/AnalysisApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Run Cld File
   * @param {module:model/CldMethod} method
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link File} and HTTP response
   */
  runCldFileWithHttpInfo(method, ucs, uts, file, opts) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runCldFile"
      );
    }
    // verify the required parameter 'ucs' is set
    if (ucs === undefined || ucs === null) {
      throw new Error(
        "Missing the required parameter 'ucs' when calling runCldFile"
      );
    }
    // verify the required parameter 'uts' is set
    if (uts === undefined || uts === null) {
      throw new Error(
        "Missing the required parameter 'uts' when calling runCldFile"
      );
    }
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling runCldFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
      ucs: ucs,
      uts: uts,
      ...(opts.npReference != null && { np_reference: opts.npReference }),
      ...(opts.m0Init != null && { m0_init: opts.m0Init }),
      ...(opts.dInit != null && { d_init: opts.dInit }),
      ...(opts.alphaTInit != null && { alpha_t_init: opts.alphaTInit }),
      ...(opts.alphaCInit != null && { alpha_c_init: opts.alphaCInit }),
    };
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/cld/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Cld File
   * @param {module:model/CldMethod} method
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link File}
   */
  runCldFile(method, ucs, uts, file, opts) {
    return this.runCldFileWithHttpInfo(method, ucs, uts, file, opts).then(
      function (response_and_data) {
        return response_and_data.data;
      }
    );
  }

  /**
   * Run CLD PiecewiseLinear from SN curve fitting (AGG input)
   * @param {String} snMethod
   * @param {Number} ucs
   * @param {Number} uts
   * @param {File} file
   * @return {Promise} with data of type {@link module:model/AnalysisResult}
   */
  runCldPiecewiseLinearFromSnFileWithHttpInfo(snMethod, ucs, uts, file, opts) {
    opts = opts || {};
    let queryParams = {
      snMethod,
      ucs,
      uts,
      ...(opts.confidenceInterval != null && {
        confidenceInterval: opts.confidenceInterval,
      }),
    };
    let formParams = { file };
    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/cld/piecewiselinear-from-sn/file",
      "POST",
      {},
      queryParams,
      {},
      formParams,
      null,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  runCldPiecewiseLinearFromSnFile(snMethod, ucs, uts, file, opts) {
    return this.runCldPiecewiseLinearFromSnFileWithHttpInfo(
      snMethod,
      ucs,
      uts,
      file,
      opts
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  runCldPiecewiseNonLinearFromSnFileWithHttpInfo(
    snMethod,
    ucs,
    uts,
    file,
    opts
  ) {
    opts = opts || {};
    let queryParams = {
      snMethod,
      ucs,
      uts,
      ...(opts.confidenceInterval != null && {
        confidenceInterval: opts.confidenceInterval,
      }),
    };
    let formParams = { file };
    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/cld/piecewisenonlinear-from-sn/file",
      "POST",
      {},
      queryParams,
      {},
      formParams,
      null,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  runCldPiecewiseNonLinearFromSnFile(snMethod, ucs, uts, file, opts) {
    return this.runCldPiecewiseNonLinearFromSnFileWithHttpInfo(
      snMethod,
      ucs,
      uts,
      file,
      opts
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Cycle Counting File
   * @param {module:model/CycleCountingMethod} method
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link File} and HTTP response
   */
  runCycleCountingFileWithHttpInfo(method, file) {
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runCycleCountingFile"
      );
    }
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling runCycleCountingFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
    };
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = File;
    return this.apiClient.callApi(
      "/analysis/cycleCounting/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Cycle Counting File
   * @param {module:model/CycleCountingMethod} method
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link File}
   */
  runCycleCountingFile(method, file) {
    return this.runCycleCountingFileWithHttpInfo(method, file).then(function (
      response_and_data
    ) {
      return response_and_data.data;
    });
  }

  /**
   * Run Damage Summation File
   * @param {module:model/DamageSummationMethod} method
   * @param {File} sncFile
   * @param {File} cycFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link File} and HTTP response
   */
  runDamageSummationFileWithHttpInfo(method, sncFile, cycFile) {
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runDamageSummationFile"
      );
    }
    // verify the required parameter 'sncFile' is set
    if (sncFile === undefined || sncFile === null) {
      throw new Error(
        "Missing the required parameter 'sncFile' when calling runDamageSummationFile"
      );
    }
    // verify the required parameter 'cycFile' is set
    if (cycFile === undefined || cycFile === null) {
      throw new Error(
        "Missing the required parameter 'cycFile' when calling runDamageSummationFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
    };
    let headerParams = {};
    let formParams = {
      sncFile: sncFile,
      cycFile: cycFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = File;
    return this.apiClient.callApi(
      "/analysis/damageSummation/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Damage Summation File
   * @param {module:model/DamageSummationMethod} method
   * @param {File} sncFile
   * @param {File} cycFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link File}
   */
  runDamageSummationFile(method, sncFile, cycFile) {
    return this.runDamageSummationFileWithHttpInfo(
      method,
      sncFile,
      cycFile
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure File
   * @param {module:model/FatigueFailureMethod} method
   * @param {module:model/FatigueModel} snModel
   * @param {Number} desirableAngle
   * @param {Number} offAxisAngle
   * @param {File} xFile
   * @param {File} yFile
   * @param {File} fFile
   * @param {Object} opts Optional parameters, used by HashinRotem
   * @param {Number} opts.offAxisAngle2
   * @param {Number} opts.tensileTransverseStrength
   * @param {Number} opts.compressiveTransverseStrength
   * @param {Number} opts.shearStrength
   * @param {Number} opts.tensileStrength1
   * @param {Number} opts.compressiveStrength1
   * @param {Number} opts.tensileStrength2
   * @param {Number} opts.compressiveStrength2
   * @param {Number} opts.tensileStrengthAtDesirableAngle
   * @param {Number} opts.compressiveStrengthAtDesirableAngle
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureFileWithHttpInfo(
    method,
    snModel,
    desirableAngle,
    offAxisAngle,
    xFile,
    yFile,
    fFile,
    opts
  ) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'snModel' is set
    if (snModel === undefined || snModel === null) {
      throw new Error(
        "Missing the required parameter 'snModel' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'desirableAngle' is set
    if (desirableAngle === undefined || desirableAngle === null) {
      throw new Error(
        "Missing the required parameter 'desirableAngle' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'offAxisAngle' is set
    if (offAxisAngle === undefined || offAxisAngle === null) {
      throw new Error(
        "Missing the required parameter 'offAxisAngle' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'xFile' is set
    if (xFile === undefined || xFile === null) {
      throw new Error(
        "Missing the required parameter 'xFile' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'yFile' is set
    if (yFile === undefined || yFile === null) {
      throw new Error(
        "Missing the required parameter 'yFile' when calling runFatigueFailureFile"
      );
    }
    // verify the required parameter 'fFile' is set
    if (fFile === undefined || fFile === null) {
      throw new Error(
        "Missing the required parameter 'fFile' when calling runFatigueFailureFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
      snModel: snModel,
      desirableAngle: desirableAngle,
      offAxisAngle: offAxisAngle,
      ...(opts.offAxisAngle2 != null && { offAxisAngle2: opts.offAxisAngle2 }),
      ...(opts.tensileTransverseStrength != null && {
        tensile_transverse_strength: opts.tensileTransverseStrength,
      }),
      ...(opts.compressiveTransverseStrength != null && {
        compressive_transverse_strength: opts.compressiveTransverseStrength,
      }),
      ...(opts.shearStrength != null && { shear_strength: opts.shearStrength }),
      ...(opts.tensileStrength1 != null && {
        tensile_strength1: opts.tensileStrength1,
      }),
      ...(opts.compressiveStrength1 != null && {
        compressive_strength1: opts.compressiveStrength1,
      }),
      ...(opts.tensileStrength2 != null && {
        tensile_strength2: opts.tensileStrength2,
      }),
      ...(opts.compressiveStrength2 != null && {
        compressive_strength2: opts.compressiveStrength2,
      }),
      ...(opts.tensileStrengthAtDesirableAngle != null && {
        tensile_strength_at_desirable_angle:
          opts.tensileStrengthAtDesirableAngle,
      }),
      ...(opts.compressiveStrengthAtDesirableAngle != null && {
        compressive_strength_at_desirable_angle:
          opts.compressiveStrengthAtDesirableAngle,
      }),
    };
    let headerParams = {};
    let formParams = {
      xFile: xFile,
      yFile: yFile,
      fFile: fFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure File
   * @param {module:model/FatigueFailureMethod} method
   * @param {module:model/FatigueModel} snModel
   * @param {Number} desirableAngle
   * @param {Number} offAxisAngle
   * @param {File} xFile
   * @param {File} yFile
   * @param {File} fFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureFile(
    method,
    snModel,
    desirableAngle,
    offAxisAngle,
    xFile,
    yFile,
    fFile,
    opts
  ) {
    return this.runFatigueFailureFileWithHttpInfo(
      method,
      snModel,
      desirableAngle,
      offAxisAngle,
      xFile,
      yFile,
      fFile,
      opts
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure ShokriehTaheri File
   * @param {Number} referenceAngle
   * @param {Number} referenceStressRatio
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} tensileAxialStrength
   * @param {Number} compressiveAxialStrength
   * @param {Number} tensileTransverseStrength
   * @param {Number} compressiveTransverseStrength
   * @param {Number} shearStrength
   * @param {File} aggFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureShokriehTaheriFileWithHttpInfo(
    referenceAngle,
    referenceStressRatio,
    desirableAngle,
    targetStressRatio,
    tensileAxialStrength,
    compressiveAxialStrength,
    tensileTransverseStrength,
    compressiveTransverseStrength,
    shearStrength,
    aggFile
  ) {
    let postBody = null;
    // verify the required parameter 'aggFile' is set
    if (aggFile === undefined || aggFile === null) {
      throw new Error(
        "Missing the required parameter 'aggFile' when calling runFatigueFailureShokriehTaheriFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      referenceAngle: referenceAngle,
      referenceStressRatio: referenceStressRatio,
      desirableAngle: desirableAngle,
      targetStressRatio: targetStressRatio,
      tensile_axial_strength: tensileAxialStrength,
      compressive_axial_strength: compressiveAxialStrength,
      tensile_transverse_strength: tensileTransverseStrength,
      compressive_transverse_strength: compressiveTransverseStrength,
      shear_strength: shearStrength,
    };
    let headerParams = {};
    let formParams = {
      aggFile: aggFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/shokriehTaheri/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure ShokriehTaheri File
   * @param {Number} referenceAngle
   * @param {Number} referenceStressRatio
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} tensileAxialStrength
   * @param {Number} compressiveAxialStrength
   * @param {Number} tensileTransverseStrength
   * @param {Number} compressiveTransverseStrength
   * @param {Number} shearStrength
   * @param {File} aggFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureShokriehTaheriFile(
    referenceAngle,
    referenceStressRatio,
    desirableAngle,
    targetStressRatio,
    tensileAxialStrength,
    compressiveAxialStrength,
    tensileTransverseStrength,
    compressiveTransverseStrength,
    shearStrength,
    aggFile
  ) {
    return this.runFatigueFailureShokriehTaheriFileWithHttpInfo(
      referenceAngle,
      referenceStressRatio,
      desirableAngle,
      targetStressRatio,
      tensileAxialStrength,
      compressiveAxialStrength,
      tensileTransverseStrength,
      compressiveTransverseStrength,
      shearStrength,
      aggFile
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure Kawai File
   * @param {Number} referenceAngle
   * @param {Number} referenceStressRatio
   * @param {Number} referenceStaticStrength
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} tensileAxialStrength
   * @param {Number} tensileTransverseStrength
   * @param {Number} shearStrength
   * @param {File} aggFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureKawaiFileWithHttpInfo(
    referenceAngle,
    referenceStressRatio,
    referenceStaticStrength,
    desirableAngle,
    targetStressRatio,
    tensileAxialStrength,
    tensileTransverseStrength,
    shearStrength,
    aggFile
  ) {
    let postBody = null;
    // verify the required parameter 'aggFile' is set
    if (aggFile === undefined || aggFile === null) {
      throw new Error(
        "Missing the required parameter 'aggFile' when calling runFatigueFailureKawaiFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      referenceAngle: referenceAngle,
      referenceStressRatio: referenceStressRatio,
      referenceStaticStrength: referenceStaticStrength,
      desirableAngle: desirableAngle,
      targetStressRatio: targetStressRatio,
      tensile_axial_strength: tensileAxialStrength,
      tensile_transverse_strength: tensileTransverseStrength,
      shear_strength: shearStrength,
    };
    let headerParams = {};
    let formParams = {
      aggFile: aggFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/kawai/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure Kawai File
   * @param {Number} referenceAngle
   * @param {Number} referenceStressRatio
   * @param {Number} referenceStaticStrength
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} tensileAxialStrength
   * @param {Number} tensileTransverseStrength
   * @param {Number} shearStrength
   * @param {File} aggFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureKawaiFile(
    referenceAngle,
    referenceStressRatio,
    referenceStaticStrength,
    desirableAngle,
    targetStressRatio,
    tensileAxialStrength,
    tensileTransverseStrength,
    shearStrength,
    aggFile
  ) {
    return this.runFatigueFailureKawaiFileWithHttpInfo(
      referenceAngle,
      referenceStressRatio,
      referenceStaticStrength,
      desirableAngle,
      targetStressRatio,
      tensileAxialStrength,
      tensileTransverseStrength,
      shearStrength,
      aggFile
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Fatigue Failure FawazEllyin File
   * @param {module:model/FatigueModel} snModel
   * @param {Number} referenceAngle
   * @param {Number} referenceStaticStrength
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} targetStaticStrength
   * @param {File} sncFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runFatigueFailureFawazEllyinFileWithHttpInfo(
    snModel,
    referenceAngle,
    referenceStaticStrength,
    desirableAngle,
    targetStressRatio,
    targetStaticStrength,
    sncFile
  ) {
    let postBody = null;
    // verify the required parameter 'sncFile' is set
    if (sncFile === undefined || sncFile === null) {
      throw new Error(
        "Missing the required parameter 'sncFile' when calling runFatigueFailureFawazEllyinFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      snModel: snModel,
      referenceAngle: referenceAngle,
      referenceStaticStrength: referenceStaticStrength,
      desirableAngle: desirableAngle,
      targetStressRatio: targetStressRatio,
      targetStaticStrength: targetStaticStrength,
    };
    let headerParams = {};
    let formParams = {
      sncFile: sncFile,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/fatigueFailure/fawazEllyin/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Fatigue Failure FawazEllyin File
   * @param {module:model/FatigueModel} snModel
   * @param {Number} referenceAngle
   * @param {Number} referenceStaticStrength
   * @param {Number} desirableAngle
   * @param {Number} targetStressRatio
   * @param {Number} targetStaticStrength
   * @param {File} sncFile
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runFatigueFailureFawazEllyinFile(
    snModel,
    referenceAngle,
    referenceStaticStrength,
    desirableAngle,
    targetStressRatio,
    targetStaticStrength,
    sncFile
  ) {
    return this.runFatigueFailureFawazEllyinFileWithHttpInfo(
      snModel,
      referenceAngle,
      referenceStaticStrength,
      desirableAngle,
      targetStressRatio,
      targetStaticStrength,
      sncFile
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Run Sn Curve File
   * @param {module:model/SnCurveMethod} method
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnalysisResult} and HTTP response
   */
  runSnCurveFileWithHttpInfo(method, file, confidenceInterval = null) {
    let postBody = null;
    // verify the required parameter 'method' is set
    if (method === undefined || method === null) {
      throw new Error(
        "Missing the required parameter 'method' when calling runSnCurveFile"
      );
    }
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling runSnCurveFile"
      );
    }

    let pathParams = {};
    let queryParams = {
      method: method,
    };

    if (confidenceInterval !== null && confidenceInterval !== undefined) {
      queryParams.confidenceInterval = confidenceInterval;
    }
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = AnalysisResult;
    return this.apiClient.callApi(
      "/analysis/snCurve/file",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Run Sn Curve File
   * @param {module:model/SnCurveMethod} method
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnalysisResult}
   */
  runSnCurveFile(method, file, confidenceInterval = null) {
    return this.runSnCurveFileWithHttpInfo(
      method,
      file,
      confidenceInterval
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }
}
