/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import AppInfo from "../model/AppInfo";
import UnitInfo from "../model/UnitInfo";

/**
 * Default service.
 * @module api/DefaultApi
 * @version 0.1.0
 */
export default class DefaultApi {
  /**
   * Constructs a new DefaultApi.
   * @alias module:api/DefaultApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Download Zip
   * @param {String} folderName
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
   */
  downloadZipDownloadsZipGetWithHttpInfo(folderName) {
    let postBody = null;
    // verify the required parameter 'folderName' is set
    if (folderName === undefined || folderName === null) {
      throw new Error(
        "Missing the required parameter 'folderName' when calling downloadZipDownloadsZipGet"
      );
    }

    let pathParams = {};
    let queryParams = {
      folder_name: folderName,
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = Object;
    return this.apiClient.callApi(
      "/downloads_zip",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Download Zip
   * @param {String} folderName
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
   */
  downloadZipDownloadsZipGet(folderName) {
    return this.downloadZipDownloadsZipGetWithHttpInfo(folderName).then(
      function (response_and_data) {
        return response_and_data.data;
      }
    );
  }

  /**
   * Get Units
   * Get All standardized units
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UnitInfo>} and HTTP response
   */
  getUnitsWithHttpInfo() {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = [UnitInfo];
    return this.apiClient.callApi(
      "/units",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Get Units
   * Get All standardized units
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UnitInfo>}
   */
  getUnits() {
    return this.getUnitsWithHttpInfo().then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Integrate Dataset
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
   */
  integrateDatasetExperimentsIntegrateDatasetPostWithHttpInfo(file) {
    let postBody = null;
    // verify the required parameter 'file' is set
    if (file === undefined || file === null) {
      throw new Error(
        "Missing the required parameter 'file' when calling integrateDatasetExperimentsIntegrateDatasetPost"
      );
    }

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {
      file: file,
    };

    let authNames = [];
    let contentTypes = ["multipart/form-data"];
    let accepts = ["application/json"];
    let returnType = Object;
    return this.apiClient.callApi(
      "/experiments/integrate_dataset",
      "POST",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Integrate Dataset
   * @param {File} file
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
   */
  integrateDatasetExperimentsIntegrateDatasetPost(file) {
    return this.integrateDatasetExperimentsIntegrateDatasetPostWithHttpInfo(
      file
    ).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Root
   * Get AppInfo
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AppInfo} and HTTP response
   */
  rootWithHttpInfo() {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = AppInfo;
    return this.apiClient.callApi(
      "/",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Root
   * Get AppInfo
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AppInfo}
   */
  root() {
    return this.rootWithHttpInfo().then(function (response_and_data) {
      return response_and_data.data;
    });
  }
}
