/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Ccfatigue);
  }
})(this, function (expect, Ccfatigue) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new Ccfatigue.QuasiStaticTest();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("QuasiStaticTest", function () {
    it("should create an instance of QuasiStaticTest", function () {
      // uncomment below and update the code to test QuasiStaticTest
      //var instance = new Ccfatigue.QuasiStaticTest();
      //expect(instance).to.be.a(Ccfatigue.QuasiStaticTest);
    });

    it('should have the property machineDisplacement (base name: "machine_displacement")', function () {
      // uncomment below and update the code to test the property machineDisplacement
      //var instance = new Ccfatigue.QuasiStaticTest();
      //expect(instance).to.be();
    });

    it('should have the property machineLoad (base name: "machine_load")', function () {
      // uncomment below and update the code to test the property machineLoad
      //var instance = new Ccfatigue.QuasiStaticTest();
      //expect(instance).to.be();
    });

    it('should have the property crackDisplacement (base name: "crack_displacement")', function () {
      // uncomment below and update the code to test the property crackDisplacement
      //var instance = new Ccfatigue.QuasiStaticTest();
      //expect(instance).to.be();
    });

    it('should have the property crackLoad (base name: "crack_load")', function () {
      // uncomment below and update the code to test the property crackLoad
      //var instance = new Ccfatigue.QuasiStaticTest();
      //expect(instance).to.be();
    });

    it('should have the property crackLength (base name: "crack_length")', function () {
      // uncomment below and update the code to test the property crackLength
      //var instance = new Ccfatigue.QuasiStaticTest();
      //expect(instance).to.be();
    });
  });
});
