/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Ccfatigue);
  }
})(this, function (expect, Ccfatigue) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new Ccfatigue.TestResult();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("TestResult", function () {
    it("should create an instance of TestResult", function () {
      // uncomment below and update the code to test TestResult
      //var instance = new Ccfatigue.TestResult();
      //expect(instance).to.be.a(Ccfatigue.TestResult);
    });

    it('should have the property specimenId (base name: "specimen_id")', function () {
      // uncomment below and update the code to test the property specimenId
      //var instance = new Ccfatigue.TestResult();
      //expect(instance).to.be();
    });

    it('should have the property totalDissipatedEnergy (base name: "total_dissipated_energy")', function () {
      // uncomment below and update the code to test the property totalDissipatedEnergy
      //var instance = new Ccfatigue.TestResult();
      //expect(instance).to.be();
    });

    it('should have the property hysteresisLoops (base name: "hysteresis_loops")', function () {
      // uncomment below and update the code to test the property hysteresisLoops
      //var instance = new Ccfatigue.TestResult();
      //expect(instance).to.be();
    });

    it('should have the property nCycles (base name: "n_cycles")', function () {
      // uncomment below and update the code to test the property nCycles
      //var instance = new Ccfatigue.TestResult();
      //expect(instance).to.be();
    });

    it('should have the property creep (base name: "creep")', function () {
      // uncomment below and update the code to test the property creep
      //var instance = new Ccfatigue.TestResult();
      //expect(instance).to.be();
    });

    it('should have the property hysteresisArea (base name: "hysteresis_area")', function () {
      // uncomment below and update the code to test the property hysteresisArea
      //var instance = new Ccfatigue.TestResult();
      //expect(instance).to.be();
    });

    it('should have the property stiffness (base name: "stiffness")', function () {
      // uncomment below and update the code to test the property stiffness
      //var instance = new Ccfatigue.TestResult();
      //expect(instance).to.be();
    });
  });
});
