/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The AnalysisResult model module.
 * @module model/AnalysisResult
 * @version 0.1.0
 */
class AnalysisResult {
  /**
   * Constructs a new <code>AnalysisResult</code>.
   * @alias module:model/AnalysisResult
   * @param csvData {File}
   * @param jsonData {File}
   */
  constructor(csvData, jsonData) {
    AnalysisResult.initialize(this, csvData, jsonData);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, csvData, jsonData) {
    obj["csv_data"] = csvData;
    obj["json_data"] = jsonData;
  }

  /**
   * Constructs a <code>AnalysisResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnalysisResult} obj Optional instance to populate.
   * @return {module:model/AnalysisResult} The populated <code>AnalysisResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnalysisResult();

      if (data.hasOwnProperty("csv_data")) {
        obj["csv_data"] = ApiClient.convertToType(data["csv_data"], File);
      }
      if (data.hasOwnProperty("json_data")) {
        obj["json_data"] = ApiClient.convertToType(data["json_data"], File);
      }
    }
    return obj;
  }
}

/**
 * @member {File} csv_data
 */
AnalysisResult.prototype["csv_data"] = undefined;

/**
 * @member {File} json_data
 */
AnalysisResult.prototype["json_data"] = undefined;

export default AnalysisResult;
