/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The EchartLine model module.
 * @module model/EchartLine
 * @version 0.1.0
 */
class EchartLine {
  /**
   * Constructs a new <code>EchartLine</code>.
   * @alias module:model/EchartLine
   * @param name {String}
   * @param xData {Array.<Number>}
   * @param yData {Array.<Number>}
   */
  constructor(name, xData, yData) {
    EchartLine.initialize(this, name, xData, yData);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, name, xData, yData) {
    obj["name"] = name;
    obj["xData"] = xData;
    obj["yData"] = yData;
  }

  /**
   * Constructs a <code>EchartLine</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EchartLine} obj Optional instance to populate.
   * @return {module:model/EchartLine} The populated <code>EchartLine</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EchartLine();

      if (data.hasOwnProperty("name")) {
        obj["name"] = ApiClient.convertToType(data["name"], "String");
      }
      if (data.hasOwnProperty("xData")) {
        obj["xData"] = ApiClient.convertToType(data["xData"], ["Number"]);
      }
      if (data.hasOwnProperty("yData")) {
        obj["yData"] = ApiClient.convertToType(data["yData"], ["Number"]);
      }
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
EchartLine.prototype["name"] = undefined;

/**
 * @member {Array.<Number>} xData
 */
EchartLine.prototype["xData"] = undefined;

/**
 * @member {Array.<Number>} yData
 */
EchartLine.prototype["yData"] = undefined;

export default EchartLine;
