/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The ExperimentModel model module.
 * @module model/ExperimentModel
 * @version 0.1.0
 */
class ExperimentModel {
  /**
   * Constructs a new <code>ExperimentModel</code>.
   * @alias module:model/ExperimentModel
   * @param id {Number}
   * @param researcher {String}
   * @param experimentType {String}
   */
  constructor(id, researcher, experimentType) {
    ExperimentModel.initialize(this, id, researcher, experimentType);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, id, researcher, experimentType) {
    obj["id"] = id;
    obj["researcher"] = researcher;
    obj["experiment_type"] = experimentType;
  }

  /**
   * Constructs a <code>ExperimentModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExperimentModel} obj Optional instance to populate.
   * @return {module:model/ExperimentModel} The populated <code>ExperimentModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExperimentModel();

      if (data.hasOwnProperty("id")) {
        obj["id"] = ApiClient.convertToType(data["id"], "Number");
      }
      if (data.hasOwnProperty("laboratory")) {
        obj["laboratory"] = ApiClient.convertToType(
          data["laboratory"],
          "String"
        );
      }
      if (data.hasOwnProperty("researcher")) {
        obj["researcher"] = ApiClient.convertToType(
          data["researcher"],
          "String"
        );
      }
      if (data.hasOwnProperty("date")) {
        obj["date"] = ApiClient.convertToType(data["date"], "String");
      }
      if (data.hasOwnProperty("experiment_type")) {
        obj["experiment_type"] = ApiClient.convertToType(
          data["experiment_type"],
          "String"
        );
      }
      if (data.hasOwnProperty("fa_experiment_type")) {
        obj["fa_experiment_type"] = ApiClient.convertToType(
          data["fa_experiment_type"],
          "String"
        );
      }
      if (data.hasOwnProperty("qs_experiment_type")) {
        obj["qs_experiment_type"] = ApiClient.convertToType(
          data["qs_experiment_type"],
          "String"
        );
      }
      if (data.hasOwnProperty("ot_experiment_type")) {
        obj["ot_experiment_type"] = ApiClient.convertToType(
          data["ot_experiment_type"],
          "String"
        );
      }
      if (data.hasOwnProperty("ot_add_info")) {
        obj["ot_add_info"] = ApiClient.convertToType(
          data["ot_add_info"],
          "String"
        );
      }
      if (data.hasOwnProperty("fracture_mode_fm")) {
        obj["fracture_mode_fm"] = ApiClient.convertToType(
          data["fracture_mode_fm"],
          "String"
        );
      }
      if (data.hasOwnProperty("fm_add_info")) {
        obj["fm_add_info"] = ApiClient.convertToType(
          data["fm_add_info"],
          "String"
        );
      }
      if (data.hasOwnProperty("control_mode")) {
        obj["control_mode"] = ApiClient.convertToType(
          data["control_mode"],
          "String"
        );
      }
      if (data.hasOwnProperty("fatigue_loading_type_flt")) {
        obj["fatigue_loading_type_flt"] = ApiClient.convertToType(
          data["fatigue_loading_type_flt"],
          "String"
        );
      }
      if (data.hasOwnProperty("flt_add_info")) {
        obj["flt_add_info"] = ApiClient.convertToType(
          data["flt_add_info"],
          "String"
        );
      }
      if (data.hasOwnProperty("measuring_equipment")) {
        obj["measuring_equipment"] = ApiClient.convertToType(
          data["measuring_equipment"],
          "String"
        );
      }
      if (data.hasOwnProperty("loading_rate")) {
        obj["loading_rate"] = ApiClient.convertToType(
          data["loading_rate"],
          "Number"
        );
      }
      if (data.hasOwnProperty("publication_doi")) {
        obj["publication_doi"] = ApiClient.convertToType(
          data["publication_doi"],
          "String"
        );
      }
      if (data.hasOwnProperty("material_tested")) {
        obj["material_tested"] = ApiClient.convertToType(
          data["material_tested"],
          "String"
        );
      }
      if (data.hasOwnProperty("material_type_sample_type")) {
        obj["material_type_sample_type"] = ApiClient.convertToType(
          data["material_type_sample_type"],
          "String"
        );
      }
      if (data.hasOwnProperty("sample_type_add_info")) {
        obj["sample_type_add_info"] = ApiClient.convertToType(
          data["sample_type_add_info"],
          "String"
        );
      }
      if (data.hasOwnProperty("material_type_fiber_material")) {
        obj["material_type_fiber_material"] = ApiClient.convertToType(
          data["material_type_fiber_material"],
          "String"
        );
      }
      if (data.hasOwnProperty("material_type_fiber_form")) {
        obj["material_type_fiber_form"] = ApiClient.convertToType(
          data["material_type_fiber_form"],
          "String"
        );
      }
      if (data.hasOwnProperty("material_type_area_density")) {
        obj["material_type_area_density"] = ApiClient.convertToType(
          data["material_type_area_density"],
          "String"
        );
      }
      if (data.hasOwnProperty("material_type_resin")) {
        obj["material_type_resin"] = ApiClient.convertToType(
          data["material_type_resin"],
          "String"
        );
      }
      if (data.hasOwnProperty("material_type_hardener")) {
        obj["material_type_hardener"] = ApiClient.convertToType(
          data["material_type_hardener"],
          "String"
        );
      }
      if (data.hasOwnProperty("material_type_mixing_ratio")) {
        obj["material_type_mixing_ratio"] = ApiClient.convertToType(
          data["material_type_mixing_ratio"],
          "String"
        );
      }
      if (data.hasOwnProperty("other_polymers_add_info")) {
        obj["other_polymers_add_info"] = ApiClient.convertToType(
          data["other_polymers_add_info"],
          "String"
        );
      }
      if (data.hasOwnProperty("curing_time")) {
        obj["curing_time"] = ApiClient.convertToType(
          data["curing_time"],
          "Number"
        );
      }
      if (data.hasOwnProperty("curing_temperature")) {
        obj["curing_temperature"] = ApiClient.convertToType(
          data["curing_temperature"],
          "Number"
        );
      }
      if (data.hasOwnProperty("curing_pressure")) {
        obj["curing_pressure"] = ApiClient.convertToType(
          data["curing_pressure"],
          "Number"
        );
      }
      if (data.hasOwnProperty("postcuring_time")) {
        obj["postcuring_time"] = ApiClient.convertToType(
          data["postcuring_time"],
          "Number"
        );
      }
      if (data.hasOwnProperty("postcuring_temperature")) {
        obj["postcuring_temperature"] = ApiClient.convertToType(
          data["postcuring_temperature"],
          "Number"
        );
      }
      if (data.hasOwnProperty("postcuring_pressure")) {
        obj["postcuring_pressure"] = ApiClient.convertToType(
          data["postcuring_pressure"],
          "Number"
        );
      }
      if (data.hasOwnProperty("glue")) {
        obj["glue"] = ApiClient.convertToType(data["glue"], "String");
      }
      if (data.hasOwnProperty("glue_curing_time")) {
        obj["glue_curing_time"] = ApiClient.convertToType(
          data["glue_curing_time"],
          "Number"
        );
      }
      if (data.hasOwnProperty("glue_curing_temperature")) {
        obj["glue_curing_temperature"] = ApiClient.convertToType(
          data["glue_curing_temperature"],
          "Number"
        );
      }
      if (data.hasOwnProperty("glue_curing_pressure")) {
        obj["glue_curing_pressure"] = ApiClient.convertToType(
          data["glue_curing_pressure"],
          "Number"
        );
      }
      if (data.hasOwnProperty("laminates_and_assemblies_stacking_sequence")) {
        obj["laminates_and_assemblies_stacking_sequence"] =
          ApiClient.convertToType(
            data["laminates_and_assemblies_stacking_sequence"],
            "String"
          );
      }
      if (data.hasOwnProperty("laminates_and_assemblies_fiber_volume_ratio")) {
        obj["laminates_and_assemblies_fiber_volume_ratio"] =
          ApiClient.convertToType(
            data["laminates_and_assemblies_fiber_volume_ratio"],
            "Number"
          );
      }
      if (data.hasOwnProperty("fatigue_r_ratio")) {
        obj["fatigue_r_ratio"] = ApiClient.convertToType(
          data["fatigue_r_ratio"],
          "Number"
        );
      }
      if (data.hasOwnProperty("fatigue_frequency")) {
        obj["fatigue_frequency"] = ApiClient.convertToType(
          data["fatigue_frequency"],
          "Number"
        );
      }
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ExperimentModel.prototype["id"] = undefined;

/**
 * @member {String} laboratory
 */
ExperimentModel.prototype["laboratory"] = undefined;

/**
 * @member {String} researcher
 */
ExperimentModel.prototype["researcher"] = undefined;

/**
 * @member {String} date
 */
ExperimentModel.prototype["date"] = undefined;

/**
 * @member {String} experiment_type
 */
ExperimentModel.prototype["experiment_type"] = undefined;

/**
 * @member {String} fa_experiment_type
 */
ExperimentModel.prototype["fa_experiment_type"] = undefined;

/**
 * @member {String} qs_experiment_type
 */
ExperimentModel.prototype["qs_experiment_type"] = undefined;

/**
 * @member {String} ot_experiment_type
 */
ExperimentModel.prototype["ot_experiment_type"] = undefined;

/**
 * @member {String} ot_add_info
 */
ExperimentModel.prototype["ot_add_info"] = undefined;

/**
 * @member {String} fracture_mode_fm
 */
ExperimentModel.prototype["fracture_mode_fm"] = undefined;

/**
 * @member {String} fm_add_info
 */
ExperimentModel.prototype["fm_add_info"] = undefined;

/**
 * @member {String} control_mode
 */
ExperimentModel.prototype["control_mode"] = undefined;

/**
 * @member {String} fatigue_loading_type_flt
 */
ExperimentModel.prototype["fatigue_loading_type_flt"] = undefined;

/**
 * @member {String} flt_add_info
 */
ExperimentModel.prototype["flt_add_info"] = undefined;

/**
 * @member {String} measuring_equipment
 */
ExperimentModel.prototype["measuring_equipment"] = undefined;

/**
 * @member {Number} loading_rate
 */
ExperimentModel.prototype["loading_rate"] = undefined;

/**
 * @member {String} publication_doi
 */
ExperimentModel.prototype["publication_doi"] = undefined;

/**
 * @member {String} material_tested
 */
ExperimentModel.prototype["material_tested"] = undefined;

/**
 * @member {String} material_type_sample_type
 */
ExperimentModel.prototype["material_type_sample_type"] = undefined;

/**
 * @member {String} sample_type_add_info
 */
ExperimentModel.prototype["sample_type_add_info"] = undefined;

/**
 * @member {String} material_type_fiber_material
 */
ExperimentModel.prototype["material_type_fiber_material"] = undefined;

/**
 * @member {String} material_type_fiber_form
 */
ExperimentModel.prototype["material_type_fiber_form"] = undefined;

/**
 * @member {String} material_type_area_density
 */
ExperimentModel.prototype["material_type_area_density"] = undefined;

/**
 * @member {String} material_type_resin
 */
ExperimentModel.prototype["material_type_resin"] = undefined;

/**
 * @member {String} material_type_hardener
 */
ExperimentModel.prototype["material_type_hardener"] = undefined;

/**
 * @member {String} material_type_mixing_ratio
 */
ExperimentModel.prototype["material_type_mixing_ratio"] = undefined;

/**
 * @member {String} other_polymers_add_info
 */
ExperimentModel.prototype["other_polymers_add_info"] = undefined;

/**
 * @member {Number} curing_time
 */
ExperimentModel.prototype["curing_time"] = undefined;

/**
 * @member {Number} curing_temperature
 */
ExperimentModel.prototype["curing_temperature"] = undefined;

/**
 * @member {Number} curing_pressure
 */
ExperimentModel.prototype["curing_pressure"] = undefined;

/**
 * @member {Number} postcuring_time
 */
ExperimentModel.prototype["postcuring_time"] = undefined;

/**
 * @member {Number} postcuring_temperature
 */
ExperimentModel.prototype["postcuring_temperature"] = undefined;

/**
 * @member {Number} postcuring_pressure
 */
ExperimentModel.prototype["postcuring_pressure"] = undefined;

/**
 * @member {String} glue
 */
ExperimentModel.prototype["glue"] = undefined;

/**
 * @member {Number} glue_curing_time
 */
ExperimentModel.prototype["glue_curing_time"] = undefined;

/**
 * @member {Number} glue_curing_temperature
 */
ExperimentModel.prototype["glue_curing_temperature"] = undefined;

/**
 * @member {Number} glue_curing_pressure
 */
ExperimentModel.prototype["glue_curing_pressure"] = undefined;

/**
 * @member {String} laminates_and_assemblies_stacking_sequence
 */
ExperimentModel.prototype["laminates_and_assemblies_stacking_sequence"] =
  undefined;

/**
 * @member {Number} laminates_and_assemblies_fiber_volume_ratio
 */
ExperimentModel.prototype["laminates_and_assemblies_fiber_volume_ratio"] =
  undefined;

/**
 * @member {Number} fatigue_r_ratio
 */
ExperimentModel.prototype["fatigue_r_ratio"] = undefined;

/**
 * @member {Number} fatigue_frequency
 */
ExperimentModel.prototype["fatigue_frequency"] = undefined;

export default ExperimentModel;
