/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * Enum class ExperimentFieldNames.
 * @enum {}
 * @readonly
 */
export default class ExperimentFieldNames {
  /**
   * value: "experiment_type"
   * @const
   */
  experiment_type = "experiment_type";

  /**
   * value: "fa_experiment_type"
   * @const
   */
  fa_experiment_type = "fa_experiment_type";

  /**
   * value: "qs_experiment_type"
   * @const
   */
  qs_experiment_type = "qs_experiment_type";

  /**
   * value: "ot_experiment_type"
   * @const
   */
  ot_experiment_type = "ot_experiment_type";

  /**
   * value: "fracture_mode_fm"
   * @const
   */
  fracture_mode_fm = "fracture_mode_fm";

  /**
   * value: "control_mode"
   * @const
   */
  control_mode = "control_mode";

  /**
   * value: "fatigue_loading_type_flt"
   * @const
   */
  fatigue_loading_type_flt = "fatigue_loading_type_flt";

  /**
   * value: "material_tested"
   * @const
   */
  material_tested = "material_tested";

  /**
   * value: "material_type_sample_type"
   * @const
   */
  material_type_sample_type = "material_type_sample_type";

  /**
   * value: "sample_type_add_info"
   * @const
   */
  sample_type_add_info = "sample_type_add_info";

  /**
   * value: "material_type_fiber_material"
   * @const
   */
  material_type_fiber_material = "material_type_fiber_material";

  /**
   * value: "material_type_fiber_form"
   * @const
   */
  material_type_fiber_form = "material_type_fiber_form";

  /**
   * value: "material_type_area_density"
   * @const
   */
  material_type_area_density = "material_type_area_density";

  /**
   * value: "material_type_resin"
   * @const
   */
  material_type_resin = "material_type_resin";

  /**
   * value: "material_type_hardener"
   * @const
   */
  material_type_hardener = "material_type_hardener";

  /**
   * value: "material_type_mixing_ratio"
   * @const
   */
  material_type_mixing_ratio = "material_type_mixing_ratio";

  /**
   * value: "other_polymers_add_info"
   * @const
   */
  other_polymers_add_info = "other_polymers_add_info";

  /**
   * value: "glue"
   * @const
   */
  glue = "glue";

  /**
   * value: "laminates_and_assemblies_stacking_sequence"
   * @const
   */
  laminates_and_assemblies_stacking_sequence =
    "laminates_and_assemblies_stacking_sequence";

  /**
   * value: "laminates_and_assemblies_fiber_volume_ratio"
   * @const
   */
  laminates_and_assemblies_fiber_volume_ratio =
    "laminates_and_assemblies_fiber_volume_ratio";

  /**
   * value: "fatigue_r_ratio"
   * @const
   */
  fatigue_r_ratio = "fatigue_r_ratio";

  /**
   * value: "fatigue_frequency"
   * @const
   */
  fatigue_frequency = "fatigue_frequency";

  /**
   * value: "curing_time"
   * @const
   */
  curing_time = "curing_time";

  /**
   * value: "curing_temperature"
   * @const
   */
  curing_temperature = "curing_temperature";

  /**
   * value: "curing_pressure"
   * @const
   */
  curing_pressure = "curing_pressure";

  /**
   * Returns a <code>ExperimentFieldNames</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ExperimentFieldNames} The enum <code>ExperimentFieldNames</code> value.
   */
  static constructFromObject(object) {
    return object;
  }
}
