/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import HysteresisLoop from "./HysteresisLoop";

/**
 * The FatigueTest model module.
 * @module model/FatigueTest
 * @version 0.1.0
 */
class FatigueTest {
  /**
   * Constructs a new <code>FatigueTest</code>.
   * @alias module:model/FatigueTest
   * @param specimenId {Number}
   * @param specimenName {String}
   * @param totalDissipatedEnergy {Number}
   * @param runOut {Boolean}
   * @param stressRatio {Number}
   * @param hysteresisLoops {Array.<module:model/HysteresisLoop>}
   * @param nCycles {Array.<Number>}
   * @param creep {Array.<Number>}
   * @param hysteresisArea {Array.<Number>}
   * @param stiffness {Array.<Number>}
   * @param stressAtFailure {Number}
   * @param strainAtFailure {Number}
   * @param nFail {Number}
   * @param warningMessages {Boolean}
   * @param crackLength {Array.<Number>}
   * @param crackDisplacement {Array.<Number>}
   * @param crackLoad {Array.<Number>tring}
   * @param crackNCycles {Array.<Number>}
   * @param da_dN {Array.<Number>}
   * @param G_MBT {Array.<Number>}
   * @param G_MCC {Array.<Number>}
   * @param G_ECM {Array.<Number>}
   * @param m_value_paris {Number} ! None
   * @param c_value_paris {Number} ! None
   */
  constructor(
    specimenId,
    specimenName,
    totalDissipatedEnergy,
    runOut,
    stressRatio,
    hysteresisLoops,
    nCycles,
    creep,
    hysteresisArea,
    stiffness,
    stressAtFailure,
    strainAtFailure,
    nFail,
    warningMessages,
    crackLength,
    crackDisplacement,
    crackLoad,
    crackNCycles, 
    da_dN,
    G_MBT,
    G_MCC,
    G_ECM,
    m_value_paris,
    c_value_paris,
  ) {
    FatigueTest.initialize(
      this,
      specimenId,
      specimenName,
      totalDissipatedEnergy,
      runOut,
      stressRatio,
      hysteresisLoops,
      nCycles,
      creep,
      hysteresisArea,
      stiffness,
      stressAtFailure,
      strainAtFailure,
      nFail,
      warningMessages,
      crackLength,
      crackDisplacement,
      crackLoad,
      crackNCycles,
      da_dN,
      G_MBT,
      G_MCC, 
      G_ECM,
      m_value_paris,
      c_value_paris,
    );
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(
    obj,
    specimenId,
    specimenName,
    totalDissipatedEnergy,
    runOut,
    stressRatio,
    hysteresisLoops,
    nCycles,
    creep,
    hysteresisArea,
    stiffness,
    stressAtFailure,
    strainAtFailure,
    nFail,
    warningMessages,
    crackLength,
    crackDisplacement,
    crackLoad,
    crackNCycles, 
    da_dN,
    G_MBT,
    G_MCC, 
    G_ECM,
    m_value_paris,
    c_value_paris,
  ) {
    obj["specimen_id"] = specimenId;
    obj["specimen_name"] = specimenName;
    obj["total_dissipated_energy"] = totalDissipatedEnergy;
    obj["run_out"] = runOut;
    obj["stress_ratio"] = stressRatio;
    obj["hysteresis_loops"] = hysteresisLoops;
    obj["n_cycles"] = nCycles;
    obj["creep"] = creep;
    obj["hysteresis_area"] = hysteresisArea;
    obj["stiffness"] = stiffness;
    obj["stress_at_failure"] = stressAtFailure;
    obj["strain_at_failure"] = strainAtFailure;
    obj["n_fail"] = nFail;
    obj["warning_messages"] = warningMessages;
    obj["crack_length"] = crackLength;
    obj["crack_displacement"] = crackDisplacement;
    obj["crack_load"] = crackLoad;
    obj["crack_n_cycles"] = crackNCycles;
    obj["da_dN"] = da_dN;
    obj["G_MBT"] = G_MBT;
    obj["G_MCC"] = G_MCC;
    obj["G_ECM"] = G_ECM;
    obj["m_value_paris"] = m_value_paris; // Paris law exponent
    obj["c_value_paris"] = c_value_paris; // Paris law coefficient
  }

  /**
   * Constructs a <code>FatigueTest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FatigueTest} obj Optional instance to populate.
   * @return {module:model/FatigueTest} The populated <code>FatigueTest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      console.log("Raw FatigueTest data:", data); // useful logs
      obj = obj || new FatigueTest();

      if (data.hasOwnProperty("specimen_id")) {
        obj["specimen_id"] = ApiClient.convertToType(
          data["specimen_id"],
          "Number"
        );
      }
      if (data.hasOwnProperty("specimen_name")) {
        obj["specimen_name"] = ApiClient.convertToType(
          data["specimen_name"],
          "String"
        );
      }
      if (data.hasOwnProperty("total_dissipated_energy")) {
        obj["total_dissipated_energy"] = ApiClient.convertToType(
          data["total_dissipated_energy"],
          "Number"
        );
      }
      if (data.hasOwnProperty("run_out")) {
        obj["run_out"] = ApiClient.convertToType(data["run_out"], "Boolean");
      }
      if (data.hasOwnProperty("stress_ratio")) {
        obj["stress_ratio"] = ApiClient.convertToType(
          data["stress_ratio"],
          "Number"
        );
      }
      if (data.hasOwnProperty("hysteresis_loops")) {
        obj["hysteresis_loops"] = ApiClient.convertToType(
          data["hysteresis_loops"],
          [HysteresisLoop]
        );
      }
      if (data.hasOwnProperty("n_cycles")) {
        obj["n_cycles"] = ApiClient.convertToType(data["n_cycles"], ["Number"]);
      }
      if (data.hasOwnProperty("creep")) {
        obj["creep"] = ApiClient.convertToType(data["creep"], ["Number"]);
      }
      if (data.hasOwnProperty("hysteresis_area")) {
        obj["hysteresis_area"] = ApiClient.convertToType(
          data["hysteresis_area"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("stiffness")) {
        obj["stiffness"] = ApiClient.convertToType(data["stiffness"], [
          "Number",
        ]);
      }
      if (data.hasOwnProperty("stress_at_failure")) {
        obj["stress_at_failure"] = ApiClient.convertToType(
          data["stress_at_failure"],
          "Number"
        );
      }
      if (data.hasOwnProperty("strain_at_failure")) {
        obj["strain_at_failure"] = ApiClient.convertToType(
          data["strain_at_failure"],
          "Number"
        );
      }
      if (data.hasOwnProperty("n_fail")) {
        obj["n_fail"] = ApiClient.convertToType(data["n_fail"], "Number");
      }
      if (data.hasOwnProperty("warning_messages")) {
        obj["warning_messages"] = ApiClient.convertToType(
          data["warning_messages"],
          "Boolean"
        );
      }
      if (data.hasOwnProperty("crack_length")) {
        obj["crack_length"] = ApiClient.convertToType(
          data["crack_length"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("crack_displacement")) {
        obj["crack_displacement"] = ApiClient.convertToType(
          data["crack_displacement"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("crack_load")) {
        obj["crack_load"] = ApiClient.convertToType(
          data["crack_load"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("crack_n_cycles")) {
        obj["crack_n_cycles"] = ApiClient.convertToType(
          data["crack_n_cycles"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("da_dN")) {
        obj["da_dN"] = ApiClient.convertToType(data["da_dN"], ["Number"]);
      }
      if (data.hasOwnProperty("G_MBT")) {
        obj["G_MBT"] = ApiClient.convertToType(data["G_MBT"], ["Number"]);
      }
      if (data.hasOwnProperty("G_MCC")) {
        obj["G_MCC"] = ApiClient.convertToType(data["G_MCC"], ["Number"]);
      }
      if (data.hasOwnProperty("G_ECM")) {
        obj["G_ECM"] = ApiClient.convertToType(data["G_ECM"], ["Number"]);
      }
      if (data.hasOwnProperty("m_value_paris")) {
        obj["m_value_paris"] = ApiClient.convertToType(
          data["m_value_paris"],
          "Number"
        );
      }
      if (data.hasOwnProperty("c_value_paris")) {
        obj["c_value_paris"] = ApiClient.convertToType(
          data["c_value_paris"],
          "Number"
        );
      }
    }
    console.log("Constructed FatigueTest object:", obj); // useful logs
    return obj;
  }
}

/**
 * @member {Number} specimen_id
 */
FatigueTest.prototype["specimen_id"] = undefined;

/**
 * @member {String} specimen_name
 */
FatigueTest.prototype["specimen_name"] = undefined;

/**
 * @member {Number} total_dissipated_energy
 */
FatigueTest.prototype["total_dissipated_energy"] = undefined;

/**
 * @member {Boolean} run_out
 */
FatigueTest.prototype["run_out"] = undefined;

/**
 * @member {Number} stress_ratio
 */
FatigueTest.prototype["stress_ratio"] = undefined;

/**
 * @member {Array.<module:model/HysteresisLoop>} hysteresis_loops
 */
FatigueTest.prototype["hysteresis_loops"] = undefined;

/**
 * @member {Array.<Number>} n_cycles
 */
FatigueTest.prototype["n_cycles"] = undefined;

/**
 * @member {Array.<Number>} creep
 */
FatigueTest.prototype["creep"] = undefined;

/**
 * @member {Array.<Number>} hysteresis_area
 */
FatigueTest.prototype["hysteresis_area"] = undefined;

/**
 * @member {Array.<Number>} stiffness
 */
FatigueTest.prototype["stiffness"] = undefined;

/**
 * @member {Number} stress_at_failure
 */
FatigueTest.prototype["stress_at_failure"] = undefined;

/**
 * @member {Number} strain_at_failure
 */
FatigueTest.prototype["strain_at_failure"] = undefined;

/**
 * @member {Number} n_fail
 */
FatigueTest.prototype["n_fail"] = undefined;

/**
 * @member {Boolean} warning_messages
 */
FatigueTest.prototype["warning_messages"] = undefined;

/**
 * @member {Array.<Number>} crack_length
 */
FatigueTest.prototype["crack_length"] = undefined;
/**
 * @member {Array.<Number>} crack_displacement
 */
FatigueTest.prototype["crack_displacement"] = undefined;
/**
 * @member {Array.<Number>} crack_load
 */
FatigueTest.prototype["crack_load"] = undefined;
/**
 * @member {Array.<Number>} crack_n_cycles
 */
FatigueTest.prototype["crack_n_cycles"] = undefined;
/**
 * @member {Array.<Number>} da_dN
 */
FatigueTest.prototype["da_dN"] = undefined;
/**
 * @member {Array.<Number>} G_MBT
 */
FatigueTest.prototype["G_MBT"] = undefined;
/**
 * @member {Number} m_value_paris - Paris law exponent
 */
FatigueTest.prototype["G_MCC"] = undefined;
/**
 * @member {Number} m_value_paris - Paris law exponent
 */
FatigueTest.prototype["G_ECM"] = undefined;
/**
 * @member {Number} m_value_paris - Paris law exponent
 */
FatigueTest.prototype["m_value_paris"] = undefined;
/**
 * @member {Number} c_value_paris - Paris law coefficient
 */
FatigueTest.prototype["c_value_paris"] = undefined;

export default FatigueTest;
