/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * Enum class FatigueFailureMethod.
 * @enum {}
 * @readonly
 */
export default class FatigueFailureMethod {
  /**
   * value: "FTPF"
   * @const
   */
  FTPF = "FTPF";

  /**
   * value: "HashinRotem"
   * @const
   */
  HashinRotem = "HashinRotem";

  /**
   * value: "ShokriehTaheri"
   * @const
   */
  ShokriehTaheri = "ShokriehTaheri";

  /**
   * value: "FawazEllyin"
   * @const
   */
  FawazEllyin = "FawazEllyin";

  /**
   * value: "SimsBrogdon"
   * @const
   */
  SimsBrogdon = "SimsBrogdon";

  /**
   * value: "Kawai"
   * @const
   */
  Kawai = "Kawai";

  /**
   * Returns a <code>FatigueFailureMethod</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/FatigueFailureMethod} The enum <code>FatigueFailureMethod</code> value.
   */
  static constructFromObject(object) {
    return object;
  }
}
