/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * Enum class HashinRotemPanelType.
 * @enum {}
 * @readonly
 */
export default class HashinRotemPanelType {
  /**
   * value: "Transverse"
   * @const
   */
  Transverse = "Transverse";

  /**
   * value: "Shear"
   * @const
   */
  Shear = "Shear";

  /**
   * value: "Off-axis"
   * @const
   */
  "Off-axis" = "Off-axis";

  /**
   * Returns a <code>HashinRotemPanelType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/HashinRotemPanelType} The enum <code>HashinRotemPanelType</code> value.
   */
  static constructFromObject(object) {
    return object;
  }
}
