/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The QuasiStaticTest model module.
 * @module model/QuasiStaticTest
 * @version 0.1.0
 */
class QuasiStaticTest {
  /**
   * Constructs a new <code>QuasiStaticTest</code>.
   * @alias module:model/QuasiStaticTest
   * @param specimenName {String}
   * @param specimenId {Number}
   * @param crackDisplacement {Array.<Number>}
   * @param crackLoad {Array.<Number>}
   * @param crackLength {Array.<Number>}
   * @param displacement {Object.<String, Array.<Number>>}
   * @param load {Object.<String, Array.<Number>>}
   * @param strain {Object.<String, Array.<Number>>}
   * @param stress {Object.<String, Array.<Number>>}
   * @param crackFractureenergyMbt {Array.<Number>}
   * @param crackFractureenergyMcc {Array.<Number>}
   * @param crackFractureenergyEcm {Array.<Number>}
   */
  constructor(
    specimenName,
    specimenId,
    crackDisplacement,
    crackLoad,
    crackLength,
    displacement,
    load,
    strain,
    stress,
    crackFractureenergyMbt,
    crackFractureenergyMcc,
    crackFractureenergyEcm
  ) {
    QuasiStaticTest.initialize(
      this,
      specimenName,
      specimenId,
      crackDisplacement,
      crackLoad,
      crackLength,
      displacement,
      load,
      strain,
      stress,
      crackFractureenergyMbt,
      crackFractureenergyMcc,
      crackFractureenergyEcm
    );
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(
    obj,
    specimenName,
    specimenId,
    crackDisplacement,
    crackLoad,
    crackLength,
    displacement,
    load,
    strain,
    stress,
    crackFractureenergyMbt,
    crackFractureenergyMcc,
    crackFractureenergyEcm
  ) {
    obj["specimen_name"] = specimenName;
    obj["specimen_id"] = specimenId;
    obj["crack_displacement"] = crackDisplacement;
    obj["crack_load"] = crackLoad;
    obj["crack_length"] = crackLength;
    obj["displacement"] = displacement;
    obj["load"] = load;
    obj["strain"] = strain;
    obj["stress"] = stress;
    obj["crack_fractureenergy_mbt"] = crackFractureenergyMbt;
    obj["crack_fractureenergy_mcc"] = crackFractureenergyMcc;
    obj["crack_fractureenergy_ecm"] = crackFractureenergyEcm;
  }

  /**
   * Constructs a <code>QuasiStaticTest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuasiStaticTest} obj Optional instance to populate.
   * @return {module:model/QuasiStaticTest} The populated <code>QuasiStaticTest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new QuasiStaticTest();

      if (data.hasOwnProperty("specimen_name")) {
        obj["specimen_name"] = ApiClient.convertToType(
          data["specimen_name"],
          "String"
        );
      }
      if (data.hasOwnProperty("specimen_id")) {
        obj["specimen_id"] = ApiClient.convertToType(
          data["specimen_id"],
          "Number"
        );
      }
      if (data.hasOwnProperty("crack_displacement")) {
        obj["crack_displacement"] = ApiClient.convertToType(
          data["crack_displacement"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("crack_load")) {
        obj["crack_load"] = ApiClient.convertToType(data["crack_load"], [
          "Number",
        ]);
      }
      if (data.hasOwnProperty("crack_length")) {
        obj["crack_length"] = ApiClient.convertToType(data["crack_length"], [
          "Number",
        ]);
      }
      if (data.hasOwnProperty("displacement")) {
        obj["displacement"] = ApiClient.convertToType(data["displacement"], {
          String: ["Number"],
        });
      }
      if (data.hasOwnProperty("load")) {
        obj["load"] = ApiClient.convertToType(data["load"], {
          String: ["Number"],
        });
      }
      if (data.hasOwnProperty("strain")) {
        obj["strain"] = ApiClient.convertToType(data["strain"], {
          String: ["Number"],
        });
      }
      if (data.hasOwnProperty("stress")) {
        obj["stress"] = ApiClient.convertToType(data["stress"], {
          String: ["Number"],
        });
      }
      if (data.hasOwnProperty("toughness")) {
        obj["toughness"] = ApiClient.convertToType(data["toughness"], "Number");
      }
      if (data.hasOwnProperty("initial_crack_length")) {
        obj["initial_crack_length"] = ApiClient.convertToType(
          data["initial_crack_length"],
          "Number"
        );
      }
      if (data.hasOwnProperty("young_modulus")) {
        obj["young_modulus"] = ApiClient.convertToType(
          data["young_modulus"],
          "Number"
        );
      }
      if (data.hasOwnProperty("poisson_ratio")) {
        obj["poisson_ratio"] = ApiClient.convertToType(
          data["poisson_ratio"],
          "Number"
        );
      }
      if (data.hasOwnProperty("crack_fractureenergy_mbt")) {
        obj["crack_fractureenergy_mbt"] = ApiClient.convertToType(
          data["crack_fractureenergy_mbt"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("crack_fractureenergy_mcc")) {
        obj["crack_fractureenergy_mcc"] = ApiClient.convertToType(
          data["crack_fractureenergy_mcc"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("crack_fractureenergy_ecm")) {
        obj["crack_fractureenergy_ecm"] = ApiClient.convertToType(
          data["crack_fractureenergy_ecm"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("g_init_mbt")) {
        obj["g_init_mbt"] = ApiClient.convertToType(
          data["g_init_mbt"],
          "Number"
        );
      }
      if (data.hasOwnProperty("bridginglength_mbt")) {
        obj["bridginglength_mbt"] = ApiClient.convertToType(
          data["bridginglength_mbt"],
          "Number"
        );
      }
      if (data.hasOwnProperty("g_plateau_mbt")) {
        obj["g_plateau_mbt"] = ApiClient.convertToType(
          data["g_plateau_mbt"],
          "Number"
        );
      }
      if (data.hasOwnProperty("g_init_mcc")) {
        obj["g_init_mcc"] = ApiClient.convertToType(
          data["g_init_mcc"],
          "Number"
        );
      }
      if (data.hasOwnProperty("bridginglength_mcc")) {
        obj["bridginglength_mcc"] = ApiClient.convertToType(
          data["bridginglength_mcc"],
          "Number"
        );
      }
      if (data.hasOwnProperty("g_plateau_mcc")) {
        obj["g_plateau_mcc"] = ApiClient.convertToType(
          data["g_plateau_mcc"],
          "Number"
        );
      }
      if (data.hasOwnProperty("g_init_ecm")) {
        obj["g_init_ecm"] = ApiClient.convertToType(
          data["g_init_ecm"],
          "Number"
        );
      }
      if (data.hasOwnProperty("bridginglength_ecm")) {
        obj["bridginglength_ecm"] = ApiClient.convertToType(
          data["bridginglength_ecm"],
          "Number"
        );
      }
      if (data.hasOwnProperty("g_plateau_ecm")) {
        obj["g_plateau_ecm"] = ApiClient.convertToType(
          data["g_plateau_ecm"],
          "Number"
        );
      }
    }
    return obj;
  }
}

/**
 * @member {String} specimen_name
 */
QuasiStaticTest.prototype["specimen_name"] = undefined;

/**
 * @member {Number} specimen_id
 */
QuasiStaticTest.prototype["specimen_id"] = undefined;

/**
 * @member {Array.<Number>} crack_displacement
 */
QuasiStaticTest.prototype["crack_displacement"] = undefined;

/**
 * @member {Array.<Number>} crack_load
 */
QuasiStaticTest.prototype["crack_load"] = undefined;

/**
 * @member {Array.<Number>} crack_length
 */
QuasiStaticTest.prototype["crack_length"] = undefined;

/**
 * @member {Object.<String, Array.<Number>>} displacement
 */
QuasiStaticTest.prototype["displacement"] = undefined;

/**
 * @member {Object.<String, Array.<Number>>} load
 */
QuasiStaticTest.prototype["load"] = undefined;

/**
 * @member {Object.<String, Array.<Number>>} strain
 */
QuasiStaticTest.prototype["strain"] = undefined;

/**
 * @member {Object.<String, Array.<Number>>} stress
 */
QuasiStaticTest.prototype["stress"] = undefined;

/**
 * @member {Number} toughness
 */
QuasiStaticTest.prototype["toughness"] = undefined;

/**
 * @member {Number} initial_crack_length
 */
QuasiStaticTest.prototype["initial_crack_length"] = undefined;

/**
 * @member {Number} young_modulus
 */
QuasiStaticTest.prototype["young_modulus"] = undefined;

/**
 * @member {Number} poisson_ratio
 */
QuasiStaticTest.prototype["poisson_ratio"] = undefined;

/**
 * @member {Array.<Number>} crack_fractureenergy_mbt
 */
QuasiStaticTest.prototype["crack_fractureenergy_mbt"] = undefined;

/**
 * @member {Array.<Number>} crack_fractureenergy_mcc
 */
QuasiStaticTest.prototype["crack_fractureenergy_mcc"] = undefined;

/**
 * @member {Array.<Number>} crack_fractureenergy_ecm
 */
QuasiStaticTest.prototype["crack_fractureenergy_ecm"] = undefined;

/**
 * @member {Number} g_init_mbt
 */
QuasiStaticTest.prototype["g_init_mbt"] = undefined;

/**
 * @member {Number} bridginglength_mbt
 */
QuasiStaticTest.prototype["bridginglength_mbt"] = undefined;

/**
 * @member {Number} g_plateau_mbt
 */
QuasiStaticTest.prototype["g_plateau_mbt"] = undefined;

/**
 * @member {Number} g_init_mcc
 */
QuasiStaticTest.prototype["g_init_mcc"] = undefined;

/**
 * @member {Number} bridginglength_mcc
 */
QuasiStaticTest.prototype["bridginglength_mcc"] = undefined;

/**
 * @member {Number} g_plateau_mcc
 */
QuasiStaticTest.prototype["g_plateau_mcc"] = undefined;

/**
 * @member {Number} g_init_ecm
 */
QuasiStaticTest.prototype["g_init_ecm"] = undefined;

/**
 * @member {Number} bridginglength_ecm
 */
QuasiStaticTest.prototype["bridginglength_ecm"] = undefined;

/**
 * @member {Number} g_plateau_ecm
 */
QuasiStaticTest.prototype["g_plateau_ecm"] = undefined;

export default QuasiStaticTest;
