/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The QuasiStaticTest model module.
 * @module model/QuasiStaticTest
 * @version 0.1.0
 */
class QuasiStaticTest {
  /**
   * Constructs a new <code>QuasiStaticTest</code>.
   * @alias module:model/QuasiStaticTest
   * @param machineDisplacement {Array.<Number>}
   * @param machineLoad {Array.<Number>}
   * @param crackDisplacement {Array.<Number>}
   * @param crackLoad {Array.<Number>}
   * @param crackLength {Array.<Number>}
   * @param strain {Object.<String, Array.<Number>>}
   * @param stress {Object.<String, Array.<Number>>}
   */
  constructor(
    machineDisplacement,
    machineLoad,
    crackDisplacement,
    crackLoad,
    crackLength,
    strain,
    stress
  ) {
    QuasiStaticTest.initialize(
      this,
      machineDisplacement,
      machineLoad,
      crackDisplacement,
      crackLoad,
      crackLength,
      strain,
      stress
    );
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(
    obj,
    machineDisplacement,
    machineLoad,
    crackDisplacement,
    crackLoad,
    crackLength,
    strain,
    stress
  ) {
    obj["machine_displacement"] = machineDisplacement;
    obj["machine_load"] = machineLoad;
    obj["crack_displacement"] = crackDisplacement;
    obj["crack_load"] = crackLoad;
    obj["crack_length"] = crackLength;
    obj["strain"] = strain;
    obj["stress"] = stress;
  }

  /**
   * Constructs a <code>QuasiStaticTest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QuasiStaticTest} obj Optional instance to populate.
   * @return {module:model/QuasiStaticTest} The populated <code>QuasiStaticTest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new QuasiStaticTest();

      if (data.hasOwnProperty("machine_displacement")) {
        obj["machine_displacement"] = ApiClient.convertToType(
          data["machine_displacement"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("machine_load")) {
        obj["machine_load"] = ApiClient.convertToType(data["machine_load"], [
          "Number",
        ]);
      }
      if (data.hasOwnProperty("crack_displacement")) {
        obj["crack_displacement"] = ApiClient.convertToType(
          data["crack_displacement"],
          ["Number"]
        );
      }
      if (data.hasOwnProperty("crack_load")) {
        obj["crack_load"] = ApiClient.convertToType(data["crack_load"], [
          "Number",
        ]);
      }
      if (data.hasOwnProperty("crack_length")) {
        obj["crack_length"] = ApiClient.convertToType(data["crack_length"], [
          "Number",
        ]);
      }
      if (data.hasOwnProperty("strain")) {
        obj["strain"] = ApiClient.convertToType(data["strain"], {
          String: ["Number"],
        });
      }
      if (data.hasOwnProperty("stress")) {
        obj["stress"] = ApiClient.convertToType(data["stress"], {
          String: ["Number"],
        });
      }
    }
    return obj;
  }
}

/**
 * @member {Array.<Number>} machine_displacement
 */
QuasiStaticTest.prototype["machine_displacement"] = undefined;

/**
 * @member {Array.<Number>} machine_load
 */
QuasiStaticTest.prototype["machine_load"] = undefined;

/**
 * @member {Array.<Number>} crack_displacement
 */
QuasiStaticTest.prototype["crack_displacement"] = undefined;

/**
 * @member {Array.<Number>} crack_load
 */
QuasiStaticTest.prototype["crack_load"] = undefined;

/**
 * @member {Array.<Number>} crack_length
 */
QuasiStaticTest.prototype["crack_length"] = undefined;

/**
 * @member {Object.<String, Array.<Number>>} strain
 */
QuasiStaticTest.prototype["strain"] = undefined;

/**
 * @member {Object.<String, Array.<Number>>} stress
 */
QuasiStaticTest.prototype["stress"] = undefined;

export default QuasiStaticTest;
