/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * Enum class SnCurveMethod.
 * @enum {}
 * @readonly
 */
export default class SnCurveMethod {
    /**
     * value: "LinLog"
     * @const
     */
    LinLog = "LinLog";

    /**
     * value: "LogLog"
     * @const
     */
    LogLog = "LogLog";

    /**
     * value: "Sendeckyj"
     * @const
     */
    Sendeckyj = "Sendeckyj";

    /**
     * Returns a <code>SnCurveMethod</code> enum value from a Javascript object name.
     * @param {Object} data The plain JavaScript object containing the name of the enum value.
     * @return {module:model/SnCurveMethod} The enum <code>SnCurveMethod</code> value.
     */
    static constructFromObject(object) {
        return object;
    }
}
