/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * Enum class SnModel.
 * @enum {}
 * @readonly
 */
export default class SnModel {
  /**
   * value: "Lin-Log"
   * @const
   */
  "Lin-Log" = "Lin-Log";

  /**
   * value: "Log-Log"
   * @const
   */
  "Log-Log" = "Log-Log";

  /**
   * Returns a <code>SnModel</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/SnModel} The enum <code>SnModel</code> value.
   */
  static constructFromObject(object) {
    return object;
  }
}
