/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The UnitInfo model module.
 * @module model/UnitInfo
 * @version 0.1.0
 */
class UnitInfo {
  /**
   * Constructs a new <code>UnitInfo</code>.
   * Unit Info
   * @alias module:model/UnitInfo
   * @param subject {String}
   * @param unit {String}
   */
  constructor(subject, unit) {
    UnitInfo.initialize(this, subject, unit);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, subject, unit) {
    obj["subject"] = subject;
    obj["unit"] = unit;
  }

  /**
   * Constructs a <code>UnitInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnitInfo} obj Optional instance to populate.
   * @return {module:model/UnitInfo} The populated <code>UnitInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UnitInfo();

      if (data.hasOwnProperty("subject")) {
        obj["subject"] = ApiClient.convertToType(data["subject"], "String");
      }
      if (data.hasOwnProperty("unit")) {
        obj["unit"] = ApiClient.convertToType(data["unit"], "String");
      }
    }
    return obj;
  }
}

/**
 * @member {String} subject
 */
UnitInfo.prototype["subject"] = undefined;

/**
 * @member {String} unit
 */
UnitInfo.prototype["unit"] = undefined;

export default UnitInfo;
