"""initial tables

Revision ID: bc844f67d80f
Revises:
Create Date: 2021-11-30 13:31:40.132219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc844f67d80f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("laboratory", sa.String(), nullable=True),
        sa.Column("researcher", sa.String(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("experiment_type", sa.String(), nullable=True),
        sa.Column("fracture", sa.Boolean(), nullable=True),
        sa.Column(
            "fracture_mode",
            sa.Enum(
                "Mode I", "Mode II", "Mode III", "Combined", "", name="fracture_mode"
            ),
            nullable=True,
        ),
        sa.Column("initial_crack_length", sa.Float(), nullable=True),
        sa.Column(
            "fatigue_test_type",
            sa.Enum("CA", "VA", "BL", "Combined", "", name="fatigue_test_type"),
            nullable=True,
        ),
        sa.Column("measuring_equipment", sa.String(), nullable=True),
        sa.Column("reliability_level", sa.Float(), nullable=True),
        sa.Column(
            "control_mode",
            sa.Enum(
                "Load Controlled", "Displacement Controlled", "", name="control_mode"
            ),
            nullable=True,
        ),
        sa.Column("publication_title", sa.String(), nullable=True),
        sa.Column("publication_author", sa.String(), nullable=True),
        sa.Column("publication_year", sa.String(), nullable=True),
        sa.Column("publication_doi", sa.String(), nullable=True),
        sa.Column("publication_images_repository", sa.String(), nullable=True),
        sa.Column("material_type_fiber_material", sa.String(), nullable=True),
        sa.Column("material_type_fiber_geometry", sa.String(), nullable=True),
        sa.Column("material_type_area_density", sa.Float(), nullable=True),
        sa.Column("material_type_resin", sa.String(), nullable=True),
        sa.Column("material_type_hardener", sa.String(), nullable=True),
        sa.Column("material_type_mixing_ratio", sa.String(), nullable=True),
        sa.Column("geometry_length", sa.Float(), nullable=True),
        sa.Column("geometry_width", sa.Float(), nullable=True),
        sa.Column("geometry_thickness", sa.Float(), nullable=True),
        sa.Column("laminates_and_assemblies_curing_time", sa.Float(), nullable=True),
        sa.Column(
            "laminates_and_assemblies_curing_temperature", sa.Float(), nullable=True
        ),
        sa.Column(
            "laminates_and_assemblies_curing_pressure", sa.Float(), nullable=True
        ),
        sa.Column("laminates_and_assemblies_fiber_content", sa.Float(), nullable=True),
        sa.Column(
            "laminates_and_assemblies_stacking_sequence", sa.String(), nullable=True
        ),
        sa.Column("test_condtions_temperature", sa.Float(), nullable=True),
        sa.Column("test_condtions_humidity", sa.Float(), nullable=True),
        sa.Column("dic_analysis_subset_size", sa.Integer(), nullable=True),
        sa.Column("dic_analysis_step_size", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("specimen_number", sa.String(), nullable=True),
        sa.Column("stress_ratio", sa.Float(), nullable=True),
        sa.Column("maximum_stress", sa.Float(), nullable=True),
        sa.Column("loading_rate", sa.Float(), nullable=True),
        sa.Column("run_out", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test")
    op.drop_table("experiment")
    # ### end Alembic commands ###
