"""initial tables

Revision ID: c88178579df5
Revises:
Create Date: 2021-11-25 15:19:25.817833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88178579df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'experiment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('laboratory', sa.String(), nullable=True),
        sa.Column('researcher', sa.String(), nullable=True),
        sa.Column('experiment_type', sa.String(), nullable=True),
        sa.Column('publication_title', sa.String(), nullable=True),
        sa.Column('publication_doi', sa.String(), nullable=True),
        sa.Column('geometry_length', sa.Integer(), nullable=True),
        sa.Column('geometry_width', sa.Integer(), nullable=True),
        sa.Column('geometry_thickness', sa.Integer(), nullable=True),
        sa.Column('images_repository', sa.String(), nullable=True),
        sa.Column('laminates_and_assemblies_curing_time',
                  sa.Integer(), nullable=True),
        sa.Column('laminates_and_assemblies_curing_temperature',
                  sa.Integer(), nullable=True),
        sa.Column('laminates_and_assemblies_curing_pressure',
                  sa.Integer(), nullable=True),
        sa.Column('laminates_and_assemblies_fiber_content',
                  sa.Integer(), nullable=True),
        sa.Column('laminates_and_assemblies_stacking_sequence',
                  sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'test',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('experiment_id', sa.Integer(), nullable=True),
        sa.Column('specimen_number', sa.String(), nullable=True),
        sa.Column('number_of_cycles_to_failure', sa.Integer(), nullable=True),
        sa.Column('stress_at_failure', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('experiment')
    # ### end Alembic commands ###
