"""Your message that will be used

Revision ID: ceba65365eb4
Revises: e01704da37a7
Create Date: 2025-04-29 14:41:36.257917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceba65365eb4'
down_revision = 'e01704da37a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
