"""update test_measuring_point

Revision ID: e01704da37a7
Revises: a221d65efa29
Create Date: 2022-09-27 15:07:37.373716

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e01704da37a7"
down_revision = "a221d65efa29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_measuring_point",
        sa.Column("measuring_point_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_measuring_point", "measuring_point_id")
    # ### end Alembic commands ###
