"""added t and l_prime parameters for Joseph Calculation

Revision ID: e0c0f0f3af64
Revises: ceba65365eb4
Create Date: 2025-05-27 22:11:39.009608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0c0f0f3af64'
down_revision = 'ceba65365eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiment', 'material_type_area_density',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('experiment', 'publication_images_repository')
    op.drop_column('experiment', 'laminates_and_assemblies_curing_pressure')
    op.drop_column('experiment', 'laminates_and_assemblies_curing_time')
    op.drop_column('experiment', 'reliability_level')
    op.drop_column('experiment', 'publication_title')
    op.drop_column('experiment', 'measurement_measuring_points')
    op.drop_column('experiment', 'fracture')
    op.drop_column('experiment', 'publication_year')
    op.drop_column('experiment', 'quasi_static_test_type')
    op.drop_column('experiment', 'dic_analysis_step_size')
    op.drop_column('experiment', 'dic_analysis_subset_size')
    op.drop_column('experiment', 'fatigue_test_type')
    op.drop_column('experiment', 'laminates_and_assemblies_curing_temperature')
    op.drop_column('experiment', 'fracture_mode')
    op.drop_column('experiment', 'temperature_test_type')
    op.drop_column('experiment', 'publication_author')
    op.add_column('test', sa.Column('t', sa.Float(), nullable=True))
    op.add_column('test', sa.Column('l_prime', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'l_prime')
    op.drop_column('test', 't')
    op.add_column('experiment', sa.Column('publication_author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('temperature_test_type', postgresql.ENUM('DMA', 'DSC', 'FIRE', 'Unspecified', '', name='temperature_test_type'), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('fracture_mode', postgresql.ENUM('Mode I', 'Mode II', 'Mode III', 'Mixed-Mode', '', name='fracture_mode'), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('laminates_and_assemblies_curing_temperature', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('fatigue_test_type', postgresql.ENUM('CA', 'VA', 'BL', 'Combined', '', name='fatigue_test_type'), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('dic_analysis_subset_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('dic_analysis_step_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('quasi_static_test_type', postgresql.ENUM('Tensile', 'Compressive', 'Shear', 'Bending', 'Fracture', 'Unspecified', '', name='quasi_static_test_type'), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('publication_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('fracture', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('measurement_measuring_points', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('publication_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('reliability_level', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('laminates_and_assemblies_curing_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('laminates_and_assemblies_curing_pressure', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('experiment', sa.Column('publication_images_repository', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('experiment', 'material_type_area_density',
               existing_type=sa.String(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
