/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import HTTPValidationError from "../model/HTTPValidationError";
import PageExperimentModel from "../model/PageExperimentModel";

/**
 * Experiments service.
 * @module api/ExperimentsApi
 * @version 0.1.0
 */
export default class ExperimentsApi {
  /**
   * Constructs a new ExperimentsApi.
   * @alias module:api/ExperimentsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Callback function to receive the result of the getExperimentsExperimentsGet operation.
   * @callback module:api/ExperimentsApi~getExperimentsExperimentsGetCallback
   * @param {String} error Error message, if any.
   * @param {module:model/PageExperimentModel} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get Experiments
   * Get all experiments
   * @param {Object} opts Optional parameters
   * @param {String} opts.query
   * @param {String} opts.textSearch
   * @param {Number} opts.page  (default to 1)
   * @param {Number} opts.size  (default to 50)
   * @param {module:api/ExperimentsApi~getExperimentsExperimentsGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/PageExperimentModel}
   */
  getExperimentsExperimentsGet(opts, callback) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      query: opts["query"],
      text_search: opts["textSearch"],
      page: opts["page"],
      size: opts["size"],
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = PageExperimentModel;
    return this.apiClient.callApi(
      "/experiments",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }

  /**
   * Callback function to receive the result of the getFractureModeDistinctExperimentsFractureModeDistinctGet operation.
   * @callback module:api/ExperimentsApi~getFractureModeDistinctExperimentsFractureModeDistinctGetCallback
   * @param {String} error Error message, if any.
   * @param {Array.<String>} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get Fracture Mode Distinct
   * Get all distinct values for fracture_mode, sorted
   * @param {module:api/ExperimentsApi~getFractureModeDistinctExperimentsFractureModeDistinctGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link Array.<String>}
   */
  getFractureModeDistinctExperimentsFractureModeDistinctGet(callback) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = ["String"];
    return this.apiClient.callApi(
      "/experiments/fracture_mode/distinct",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }

  /**
   * Callback function to receive the result of the getLaminatesAndAssembliesStackingSequenceDistinctExperimentsLaminatesAndAssembliesStackingSequenceDistinctGet operation.
   * @callback module:api/ExperimentsApi~getLaminatesAndAssembliesStackingSequenceDistinctExperimentsLaminatesAndAssembliesStackingSequenceDistinctGetCallback
   * @param {String} error Error message, if any.
   * @param {Array.<String>} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get Laminates And Assemblies Stacking Sequence Distinct
   * Get all distinct values for laminates_and_assemblies_stacking_sequence, sorted
   * @param {module:api/ExperimentsApi~getLaminatesAndAssembliesStackingSequenceDistinctExperimentsLaminatesAndAssembliesStackingSequenceDistinctGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link Array.<String>}
   */
  getLaminatesAndAssembliesStackingSequenceDistinctExperimentsLaminatesAndAssembliesStackingSequenceDistinctGet(
    callback
  ) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = ["String"];
    return this.apiClient.callApi(
      "/experiments/laminates_and_assemblies_stacking_sequence/distinct",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }

  /**
   * Callback function to receive the result of the getMaterialTypeFiberMaterialDistinctExperimentsMaterialTypeFiberMaterialDistinctGet operation.
   * @callback module:api/ExperimentsApi~getMaterialTypeFiberMaterialDistinctExperimentsMaterialTypeFiberMaterialDistinctGetCallback
   * @param {String} error Error message, if any.
   * @param {Array.<String>} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get Material Type Fiber Material Distinct
   * Get all distinct values for material_type_fiber_material, sorted
   * @param {module:api/ExperimentsApi~getMaterialTypeFiberMaterialDistinctExperimentsMaterialTypeFiberMaterialDistinctGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link Array.<String>}
   */
  getMaterialTypeFiberMaterialDistinctExperimentsMaterialTypeFiberMaterialDistinctGet(
    callback
  ) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = ["String"];
    return this.apiClient.callApi(
      "/experiments/material_type_fiber_material/distinct",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }

  /**
   * Callback function to receive the result of the getMaterialTypeResinDistinctExperimentsMaterialTypeResinDistinctGet operation.
   * @callback module:api/ExperimentsApi~getMaterialTypeResinDistinctExperimentsMaterialTypeResinDistinctGetCallback
   * @param {String} error Error message, if any.
   * @param {Array.<String>} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get Material Type Resin Distinct
   * Get all distinct values for material_type_resin, sorted
   * @param {module:api/ExperimentsApi~getMaterialTypeResinDistinctExperimentsMaterialTypeResinDistinctGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link Array.<String>}
   */
  getMaterialTypeResinDistinctExperimentsMaterialTypeResinDistinctGet(
    callback
  ) {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = ["String"];
    return this.apiClient.callApi(
      "/experiments/material_type_resin/distinct",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }
}
