/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import HTTPValidationError from "../model/HTTPValidationError";
import PageTestModel from "../model/PageTestModel";

/**
 * Tests service.
 * @module api/TestsApi
 * @version 0.1.0
 */
export default class TestsApi {
  /**
   * Constructs a new TestsApi.
   * @alias module:api/TestsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Callback function to receive the result of the getTestsTestsGet operation.
   * @callback module:api/TestsApi~getTestsTestsGetCallback
   * @param {String} error Error message, if any.
   * @param {module:model/PageTestModel} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get Tests
   * Get all tests for specific experiment
   * @param {Number} experimentId
   * @param {Object} opts Optional parameters
   * @param {Number} opts.page  (default to 1)
   * @param {Number} opts.size  (default to 50)
   * @param {module:api/TestsApi~getTestsTestsGetCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/PageTestModel}
   */
  getTestsTestsGet(experimentId, opts, callback) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'experimentId' is set
    if (experimentId === undefined || experimentId === null) {
      throw new Error(
        "Missing the required parameter 'experimentId' when calling getTestsTestsGet"
      );
    }

    let pathParams = {};
    let queryParams = {
      experiment_id: experimentId,
      page: opts["page"],
      size: opts["size"],
    };
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ["application/json"];
    let returnType = PageTestModel;
    return this.apiClient.callApi(
      "/tests",
      "GET",
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null,
      callback
    );
  }
}
