version: "3.8"
services:
  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/database.env
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: {}
