/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
/**
 * Enum class CldMethod.
 * @enum {}
 * @readonly
 */
export default class CldMethod {
  /**
   * value: "Harris"
   * @const
   */
  Harris = "Harris";

  /**
   * Returns a <code>CldMethod</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/CldMethod} The enum <code>CldMethod</code> value.
   */
  static constructFromObject(object) {
    return object;
  }
}
