/**
 * ccfatigue
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
 * The ExperimentDataPreprocessed model module.
 * @module model/ExperimentDataPreprocessed
 * @version 0.1.0
 */
class ExperimentDataPreprocessed {
  /**
   * Constructs a new <code>ExperimentDataPreprocessed</code>.
   * @alias module:model/ExperimentDataPreprocessed
   * @param output {String}
   * @param success {Boolean}
   */
  constructor(output, success) {
    ExperimentDataPreprocessed.initialize(this, output, success);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, output, success) {
    obj["output"] = output;
    obj["success"] = success;
  }

  /**
   * Constructs a <code>ExperimentDataPreprocessed</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExperimentDataPreprocessed} obj Optional instance to populate.
   * @return {module:model/ExperimentDataPreprocessed} The populated <code>ExperimentDataPreprocessed</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExperimentDataPreprocessed();

      if (data.hasOwnProperty("output")) {
        obj["output"] = ApiClient.convertToType(data["output"], "String");
      }
      if (data.hasOwnProperty("success")) {
        obj["success"] = ApiClient.convertToType(data["success"], "Boolean");
      }
    }
    return obj;
  }
}

/**
 * @member {String} output
 */
ExperimentDataPreprocessed.prototype["output"] = undefined;

/**
 * @member {Boolean} success
 */
ExperimentDataPreprocessed.prototype["success"] = undefined;

export default ExperimentDataPreprocessed;
