# https://github.com/EPFL-ENAC/epfl-enac-deploy-action#readme
name: build-and-push

"on":
  push:
    branches:
      - ghcrio

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - Dockerfile: ./frontend/Dockerfile
            context: ./frontend
            image: ghcr.io/epfl-enac/ccfatigueplatform-frontend
          - Dockerfile: ./backend/Dockerfile
            context: ./backend
            image: ghcr.io/epfl-enac/ccfatigueplatform-backend
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image EPFL-ENAC.Agent.Service
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          build-args: |
            "API_PATH=${{ secrets.API_PATH }}"
            "API_URL=${{ secrets.API_URL }}"
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }},${{ matrix.image }}:${{ github.sha }},${{ matrix.image }}:latest
          labels: ${{ steps.meta.outputs.labels }}
