# https://github.com/EPFL-ENAC/epfl-enac-deploy-action#readme
name: deploy-prod

"on":
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: EPFL-ENAC/epfl-enac-deploy-action@main
        with:
          ENAC_IT4R_CD_environment: "prod"
          ENAC_IT4R_CD_deployment_id: "ccfatigue.epfl.ch"
          ENAC_IT4R_CD_deployment_secret: ${{ secrets.DEPLOYMENT_PROD_SECRET }}
